/**
 * 🎉 FUN PLUS — puluhan hiburan murni data lokal (offline, pasti jalan)
 * Kategori "Fun Menu".
 */
import { config } from '../config.js'
import { pickRandom } from '../lib/functions.js'

const P = config.display.prefix
const q = m => String(m.q || m.args.join(' ') || '').trim()

const TRUTH = ['Apa rahasia terbesar yang belum kamu cerita ke siapa pun?', 'Siapa orang pertama yang kamu suka?', 'Apa hal paling memalukan yang pernah kamu lakukan?', 'Kalau bisa ganti satu hal dari dirimu, apa itu?', 'Apa bohong putih terakhir yang kamu ucapkan?', 'Siapa di grup ini yang paling bikin kamu penasaran?', 'Apa mimpi teraneh yang pernah kamu alami?', 'Apa kebiasaan burukmu yang orang lain tidak tahu?']
const DARE = ['Kirim voice note nyanyi lagu anak-anak!', 'Ganti nama jadi "Aku Suka Kamu" selama 10 menit.', 'Chat orang terakhir di WA kamu dengan "aku kangen".', 'Sebut 3 kelebihan orang di sebelahmu (tag mereka).', 'Kirim stiker paling aneh yang kamu punya.', 'Ceritakan kejadian paling memalukan minggu ini.', 'Bicara pakai bahasa formal seharian di grup ini.', 'Ketik pesan berikutnya pakai satu tangan.']
const QUOTES = ['Kesuksesan adalah jumlah dari usaha kecil yang diulang setiap hari.', 'Jangan menunggu kesempatan, ciptakanlah.', 'Orang hebat bukan tidak pernah gagal, tapi tidak pernah berhenti mencoba.', 'Mimpimu tidak akan jadi kenyataan kalau kamu tidak mengejarnya.', 'Sedikit demi sedikit, lama-lama menjadi bukit.', 'Kegagalan adalah bumbu dari keberhasilan.', 'Hari ini sulit, besok lebih sulit, tapi lusa akan indah.', 'Yang penting bukan seberapa cepat, tapi seberapa konsisten.']
const PANTUN = ['Jalan-jalan ke kota Blitar,\nJangan lupa beli sukun.\nKalau kamu lagi semangat belajar,\nPasti cita-cita mudah terukir.']
const PANTUN2 = ['Buah mangga buah kuini,\nJatuh satu ke dalam kali.\nHati siapa tidak terhibur,\nMelihat kamu senyum hari ini.']
const PANTUN3 = ['Ke pasar beli buah duku,\nPulangnya mampir beli jamu.\nWalau jarak memisahkan kita,\nDoaku selalu menyertaimu.']
const BUCIN = ['Kalau kamu jadi lagu, kamu bakal jadi lagu yang aku putar berulang-ulang.', 'Aku tidak butuh Google, karena semua jawabannya ada di kamu.', 'Kamu tahu nggak bedanya kamu sama matahari? Matahari terbenam, kamu tidak pernah pergi dari pikiranku.', 'Sejak kenal kamu, aku jadi suka hujan — soalnya bikin ingat pelukan.', 'Kalau cinta itu penyakit, aku tidak mau sembuh.']
const GOMBAL = ['Kamu punya peta nggak? Aku tersesat di matamu.', 'Apakah kamu tukang parkir? Karena kamu selalu di hatiku.', 'Kamu itu kayak Wi-Fi, kalau nggak ada kamu hidupku nggak konek.', 'Boleh nggak aku pinjam bahumu? Buat bersandar selamanya.', 'Kamu percaya cinta pandangan pertama? Atau aku perlu lewat lagi?']
const MOTIVASI = ['Mulai saja dulu, sempurna belakangan.', 'Kamu lebih kuat dari yang kamu kira.', 'Satu langkah kecil hari ini lebih berarti dari seribu rencana.', 'Jangan bandingkan bab 1-mu dengan bab 20 orang lain.', 'Lelah itu wajar, berhenti itu pilihan.', 'Disiplin adalah jembatan antara tujuan dan pencapaian.']
const FAKTA = ['Madu tidak pernah basi meski disimpan ribuan tahun.', 'Otak manusia memakai sekitar 20% energi tubuh.', 'Kupu-kupu mengecap makanan lewat kakinya.', 'Ada lebih banyak bintang di alam semesta daripada butir pasir di Bumi.', 'Jantung udang terletak di kepalanya.', 'Pisang sebenarnya termasuk buah beri.', 'Kuku jari tangan tumbuh lebih cepat daripada kuku jari kaki.']
const RECEH = ['Kenapa zombie kalau nyerang bareng-bareng? Karena kalau sendiri namanya zomblo.', 'Ikan apa yang suka berhenti? Ikan pause.', 'Sayur apa yang pintar matematika? Sayur-sayur (satu-satu).', 'Kenapa keyboard nggak pernah capek? Karena dia punya banyak key-poisan.', 'Hewan apa yang paling kaya? Beruang.', 'Nasi apa yang nggak pernah salah? Nasi-benar.']

const YESNO = ['Iya', 'Tidak', 'Mungkin', 'Mungkin iya', 'Mungkin tidak', 'Pasti iya', 'Pasti tidak', '50:50', 'Tanya lagi nanti', 'Sepertinya iya']
const WHEN = ['besok', 'minggu depan', 'bulan depan', 'tahun depan', '3 hari lagi', 'sebentar lagi', 'masih lama', 'dalam waktu dekat', 'saat kamu siap', 'tidak pernah']
const HOW = ['Dengan santai', 'Dengan semangat', 'Pelan-pelan', 'Sambil ngopi', 'Bareng teman', 'Sendirian dulu', 'Pakai rencana matang', 'Nekat saja']

const ZODIAC = [['capricorn', 1, 19], ['aquarius', 2, 18], ['pisces', 3, 20], ['aries', 4, 19], ['taurus', 5, 20], ['gemini', 6, 20], ['cancer', 7, 22], ['leo', 8, 22], ['virgo', 9, 22], ['libra', 10, 22], ['scorpio', 11, 21], ['sagittarius', 12, 21]]
const ZODIAC_EMOJI = { capricorn: '♑', aquarius: '♒', pisces: '♓', aries: '♈', taurus: '♉', gemini: '♊', cancer: '♋', leo: '♌', virgo: '♍', libra: '♎', scorpio: '♏', sagittarius: '♐' }
const NAME_MEANING = ['pemimpin yang tegas', 'orang yang penyayang', 'petualang sejati', 'pemikir yang dalam', 'jiwa yang bebas', 'penolong yang tulus', 'kreatif dan penuh ide', 'setia dan dapat diandalkan', 'penuh semangat dan optimis', 'tenang dan bijaksana']

function hash (s) { let h = 0; for (const c of String(s)) h = (h * 31 + c.charCodeAt(0)) >>> 0; return h }

export const cQuotes = { command: ['katabijak', 'bijak', 'quotelokal'], category: 'Fun Menu', description: 'Kutipan penyemangat', limit: 0, run: m => m.reply('💬 "' + pickRandom(QUOTES) + '"') }
export const cPantun = { command: ['pantun'], category: 'Fun Menu', description: 'Pantun acak', limit: 0, run: m => m.reply('🪶 ' + pickRandom([PANTUN, PANTUN2, PANTUN3])) }
export const cBucin = { command: ['katagombal2', 'rayu', 'bucinlokal'], category: 'Fun Menu', description: 'Kata-kata bucin', limit: 0, run: m => m.reply('💘 ' + pickRandom(BUCIN)) }
export const cGombal = { command: ['gombal', 'gombalan'], category: 'Fun Menu', description: 'Gombalan maut', limit: 0, run: m => m.reply('😏 ' + pickRandom(GOMBAL)) }
export const cMotivasi = { command: ['motivasi', 'semangat'], category: 'Fun Menu', description: 'Kata motivasi', limit: 0, run: m => m.reply('💪 ' + pickRandom(MOTIVASI)) }
export const cFakta = { command: ['fakta', 'faktaunik', 'tahukah'], category: 'Fun Menu', description: 'Fakta unik dunia', limit: 0, run: m => m.reply('🧠 *Tahukah kamu?*\n' + pickRandom(FAKTA)) }
export const cReceh = { command: ['receh', 'joke', 'jokes', 'humor'], category: 'Fun Menu', description: 'Jokes receh', limit: 0, run: m => m.reply('😂 ' + pickRandom(RECEH)) }

export const cShip = { command: ['ship', 'cocok'], category: 'Fun Menu', description: 'Cek kecocokan dua nama (format: a|b)', limit: 0, run: m => { const [a, b] = String(m.q || '').split('|').map(s => s.trim()); if (!a || !b) return m.reply(`Format: \`${P}ship nama1|nama2\`\nContoh: \`${P}ship Budi|Siti\``); const pct = (hash(a + '|' + b) % 101); const bar = '█'.repeat(Math.round(pct / 10)) + '░'.repeat(10 - Math.round(pct / 10)); return m.reply(`💞 *COCOK-COCOKAN*\n${a} ❤️ ${b}\n${bar} *${pct}%*\n\n${pct > 75 ? 'Wah, jodoh nih!' : pct > 45 ? 'Lumayan, ada peluang!' : 'Yah, sepertinya teman saja.'}`) } }
export const cRate = { command: ['rate', 'nilai', 'seberapa'], category: 'Fun Menu', description: 'Beri nilai acak 1-10 untuk sesuatu', limit: 0, run: m => { const t = q(m); if (!t) return m.reply(`Contoh: \`${P}rate mie ayam\``); return m.reply(`⭐ Aku kasih *${t}* nilai ${(hash(t) % 10) + 1}/10!`) } }
export const cCantik = { command: ['cantikcek', 'cekcantik', 'gantengcek', 'cekganteng'], category: 'Fun Menu', description: 'Cek tingkat kecantikan/ketampanan', limit: 0, run: m => { const target = m.mentionJid?.[0] ? '@' + m.mentionJid[0].split('@')[0] : (q(m) || 'kamu'); const pct = (hash(target) % 101); return m.reply(`😍 Tingkat kecantikan/ketampanan *${target}*: *${pct}%* ${pct > 80 ? '🔥' : pct > 50 ? '✨' : '🙂'}`) } }
export const cUmur = { command: ['umurcek', 'cekumur', 'tebakumur'], category: 'Fun Menu', description: 'Tebak umur acak (untuk hiburan)', limit: 0, run: m => { const t = q(m) || 'kamu'; return m.reply(`🎂 Perkiraan umur *${t}*: *${(hash(t) % 60) + 10} tahun* (serius? nggak, ini cuma hiburan 😄)`) } }

export const cPick = { command: ['pick', 'pilih', 'pilihkan'], category: 'Fun Menu', description: 'Pilih acak dari daftar (pisahkan dengan |)', limit: 0, run: m => { const list = String(m.q || '').split('|').map(s => s.trim()).filter(Boolean); if (list.length < 2) return m.reply(`Format: \`${P}pick opsi1|opsi2|opsi3\``); return m.reply(`🎯 Aku pilih: *${pickRandom(list)}*`) } }
export const cCoin = { command: ['coinflip', 'lemparkoin', 'koin'], category: 'Fun Menu', description: 'Lempar koin (heads/tails)', limit: 0, run: m => m.reply('🪙 ' + (Math.random() < 0.5 ? '*HEADS* (Gambar)' : '*TAILS* (Angka)')) }
export const cDice = { command: ['dadu', 'roll', 'dice'], category: 'Fun Menu', description: 'Lempar dadu 1-6', limit: 0, run: m => { const n = Math.floor(Math.random() * 6) + 1; const face = ['⚀', '', '', '⚃', '⚄', ''][n - 1]; return m.reply(`${face} Dadu: *${n}*`) } }
export const cLucky = { command: ['luckynumber', 'angkahoki', 'nomorhoki'], category: 'Fun Menu', description: 'Angka hoki hari ini', limit: 0, run: m => { const a = (hash(m.sender + new Date().toDateString()) % 90) + 1; const b = (hash(m.sender + 'x') % 90) + 1; return m.reply(`🍀 Angka hokimu hari ini: *${a}* dan *${b}*`) } }

export const cApakah = { command: ['apakah', 'apakahaku'], category: 'Fun Menu', description: 'Tanya ya/tidak (magic 8-ball)', limit: 0, run: m => { const t = q(m); if (!t) return m.reply(`Contoh: \`${P}apakah aku ganteng?\``); return m.reply(` *${t}*\n→ ${pickRandom(YESNO)}`) } }
export const cKapankah = { command: ['kapankah', 'kapan'], category: 'Fun Menu', description: 'Tanya kapan sesuatu terjadi', limit: 0, run: m => { const t = q(m); if (!t) return m.reply(`Contoh: \`${P}kapankah aku kaya?\``); return m.reply(`⏳ *${t}*\n→ ${pickRandom(WHEN)}`) } }
export const cBisakah = { command: ['bisakah', 'bisatidak'], category: 'Fun Menu', description: 'Tanya bisa atau tidak', limit: 0, run: m => { const t = q(m); if (!t) return m.reply(`Contoh: \`${P}bisakah aku terbang?\``); return m.reply(`🤔 *${t}*\n→ ${pickRandom(['Bisa banget!', 'Nggak bisa.', 'Bisa, kalau usaha.', 'Mustahil.', 'Coba saja dulu.'])}`) } }
export const cBagaimana = { command: ['bagaimana', 'gimana', 'how'], category: 'Fun Menu', description: 'Tanya bagaimana caranya', limit: 0, run: m => { const t = q(m); if (!t) return m.reply(`Contoh: \`${P}bagaimana cara move on?\``); return m.reply(`🧭 *${t}*\n→ ${pickRandom(HOW)}`) } }
export const cSiapakah = { command: ['siapakah', 'siapa'], category: 'Fun Menu', description: 'Tunjuk acak satu orang (tag/daftar)', limit: 0, run: async m => { if (m.isGroup && m.group?.participants?.length) { const p = pickRandom(m.group.participants); return m.reply(`👉 Jawabannya: @${(p.id || p.lid || '').split('@')[0]}`, { mentions: [p.id] }) } const list = String(m.q || '').split('|').map(s => s.trim()).filter(Boolean); if (!list.length) return m.reply('Tag anggota grup atau kasih daftar: `' + P + 'siapakah a|b|c`'); return m.reply('👉 Jawabannya: *' + pickRandom(list) + '*') } }

export const cArtiNama = { command: ['artinama', 'artnama', 'namasaya'], category: 'Fun Menu', description: 'Arti nama (hiburan, dari hash)', limit: 0, run: m => { const t = q(m); if (!t) return m.reply(`Contoh: \`${P}artinama Budi\``); const mean = NAME_MEANING[hash(t.toLowerCase()) % NAME_MEANING.length]; const luck = (hash(t) % 100) + 1; return m.reply(`📖 *Arti nama "${t}"* (versi hiburan)\n▸ Makna: ${mean}\n▸ Skor keberuntungan: ${luck}/100`) } }
export const cZodiac = { command: ['zodiac', 'bintang', 'rasi'], category: 'Fun Menu', description: 'Cek zodiak dari tanggal (format: dd/mm)', limit: 0, run: m => { const mm2 = String(m.q || '').match(/(\d{1,2})[\/\-.](\d{1,2})/); if (!mm2) return m.reply(`Format: \`${P}zodiac 21/7\` (tanggal/bulan)`); const d = parseInt(mm2[1]), mo = parseInt(mm2[2]); let z = 'capricorn'; for (const [name, mth, cut] of ZODIAC) { if (mo === mth) { z = d <= cut ? name : ZODIAC[(ZODIAC.findIndex(x => x[0] === name) + 1) % 12][0]; break } } return m.reply(`${ZODIAC_EMOJI[z] || '✨'} Zodiakmu: *${z.toUpperCase()}*`) } }
