/**
 * 🎮 GAME MASSAL — 60 game teks sesi (v7.37.0)
 * ------------------------------------------------------------------
 *  20 tebak + 20 kuis + 10 matematika + 10 kata. Memakai penyimpanan
 *  sesi yang SAMA dengan games.js (gameSessions) sehingga jawaban
 *  langsung diproses checkGameAnswer bawaan (hadiah koin+EXP otomatis).
 */
import { config } from '../config.js'
import { gameSessions } from '../lib/gamestore.js'

const P = config.display.prefix
const TTL = 120000
const acak = (a, b) => Math.floor(Math.random() * (b - a + 1)) + a
const pilih = arr => arr[Math.floor(Math.random() * arr.length)]

function sesiAktif (jid) {
  const s = gameSessions.get(jid)
  if (!s) return null
  if (Date.now() > s.expires) { gameSessions.delete(jid); return null }
  return s
}

async function mulai (m, g, soal, jawab) {
  const jalan = sesiAktif(m.jid)
  if (jalan) return m.reply(`⏳ Masih ada game *${jalan.game}* berjalan di chat ini.\nJawab dulu, atau tunggu ${Math.ceil((jalan.expires - Date.now()) / 1000)} detik sampai expire.`)
  gameSessions.set(m.jid, { game: g.c, cmd: g.c, answer: jawab, reward: g.hadiah || 300, exp: g.exp || 40, expires: Date.now() + TTL })
  const teks = `*${g.n}*\n\n${soal}\n\n⏱️ Waktu: *120 detik*\n💰 Hadiah: ${(g.hadiah || 300).toLocaleString('id-ID')} koin + ${g.exp || 40} EXP\n\nKetik jawabanmu langsung di chat ini!`
  return m.sendButtons({ title: `🎮 ${g.n}`, text: teks, footer: config.bot.footer, buttons: [{ text: '🚫 Batalkan', id: `${P}batalgame` }] }).catch(() => m.reply(teks))
}

function buat (g) {
  return {
    command: [g.c],
    category: 'Games',
    description: `${g.n} — ${g.d}`,
    limit: 0,
    cooldown: 2,
    run: async m => {
      let soal, jawab
      if (g.gen) { [soal, jawab] = g.gen() } else { const s = pilih(g.bank); soal = s[0]; jawab = s[1] }
      return mulai(m, g, soal, jawab)
    }
  }
}

/* ---------------- generator matematika & sandi ---------------- */
const acakHuruf = s => s.split('').sort(() => Math.random() - 0.5).join('')
const GEN = {
  tambah: () => { const a = acak(11, 99), b = acak(11, 99); return [`Berapa hasil dari:\n\n*${a} + ${b} = ?*`, String(a + b)] },
  kurang: () => { const a = acak(30, 99), b = acak(11, a - 1); return [`Berapa hasil dari:\n\n*${a} − ${b} = ?*`, String(a - b)] },
  kali: () => { const a = acak(3, 12), b = acak(3, 12); return [`Berapa hasil dari:\n\n*${a} × ${b} = ?*`, String(a * b)] },
  bagi: () => { const b = acak(2, 12), h = acak(2, 12); return [`Berapa hasil dari:\n\n*${b * h} ÷ ${b} = ?*`, String(h)] },
  pangkat: () => { const a = acak(3, 15); return [`Berapa hasil dari:\n\n*${a}² = ?*`, String(a * a)] },
  akar: () => { const a = acak(3, 15); return [`Berapa hasil dari:\n\n*√${a * a} = ?*`, String(a)] },
  pecahan: () => { const d = acak(2, 9), a = acak(1, d - 1), b = acak(1, d - a); return [`Berapa hasil dari:\n\n*${a}/${d} + ${b}/${d} = ?*\n\n_(jawab pecahan: x/y)_`, `${a + b}/${d}`] },
  persen: () => { const p = pilih([10, 20, 25, 50, 75]), n = acak(2, 20) * (100 / (p === 25 || p === 75 ? 25 : p === 10 || p === 20 ? 10 : 50)); return [`Berapa hasil dari:\n\n*${p}% × ${n} = ?*`, String(Math.round(p / 100 * n))] },
  pola: () => { const t = acak(0, 3); if (t === 0) { const a = acak(2, 9), l = acak(2, 6); return [`Lanjutkan pola:\n\n*${a}, ${a + l}, ${a + l * 2}, ...?*`, String(a + l * 3)] } if (t === 1) { const a = acak(2, 5); return [`Lanjutkan pola:\n\n*${a}, ${a * 2}, ${a * 4}, ...?*`, String(a * 8)] } if (t === 2) { const a = acak(2, 6); return [`Lanjutkan pola:\n\n*${a}, ${a * a}, ${a * a * a}, ...?*\n\n_(jawab angka berikutnya bila ×${a})_`, String(a * a * a * a)] } const a = acak(1, 5), b = acak(a + 1, a + 5); return [`Lanjutkan pola:\n\n*${a}, ${b}, ${a + b}, ...?*`, String(a + b + b)] },
  suhu: () => { const c = acak(0, 8) * 5; return [`Ubah suhu:\n\n*${c}°C = ... °F?*`, String(c * 9 / 5 + 32)] },
  sandi: () => { const w = pilih(['semangat', 'merdeka', 'indonesia', 'garuda', 'pancasila', 'bhinneka']); const s = w.split('').map(x => String.fromCharCode(97 + (x.charCodeAt(0) - 97 + 3) % 26)).join(''); return [`Pecahkan sandi geser +3:\n\n*${s}*\n\n_(a→d, b→e, ...)_`, w] },
  sandiangka: () => { const w = pilih(['cinta', 'damai', 'kopi', 'rindu', 'kawan', 'senja']); return [`Pecahkan sandi angka (a=1, b=2, ...):\n\n*${w.split('').map(x => x.charCodeAt(0) - 96).join('-')}*`, w] },
  acakkalimat: () => { const k = pilih(['saya makan nasi goreng', 'ibu pergi ke pasar pagi', 'adik bermain bola sore', 'kucing tidur di kursi', 'burung terbang di langit', 'petani panen padi sawah']); let a = k; let lindung = 0; while ((a === k || a.split(' ')[0] === k.split(' ')[0]) && lindung++ < 9) a = k.split(' ').sort(() => Math.random() - 0.5).join(' '); return [`Susun kalimat acak ini:\n\n*${a}*`, k] }
}

const DAFTAR = [
  /* ===== 20 TEBAK ===== */
  { c: 'tebakalatmusik', n: '🎺 Tebak Alat Musik', d: 'Tebak alat musik dari petunjuk', hadiah: 350, exp: 45, bank: [['Bunyi "jreng", dipetik 6 senar 🎸', 'gitar'], ['Ditiup, dari bambu, khas Sunda 🎋', ['suling', 'seruling']], ['Dipukul, bundar besar 🥁', ['drum', 'gendang']], ['Digesek 4 senar 🎻', 'biola'], ['Ditekan tuts hitam putih 🎹', ['piano', 'pianika', 'keyboard']], ['Ditiup mirip terompet kecil 🎺', 'terompet'], ['Dipetik khas Hawaii, kecil 🌺', 'ukulele'], ['Gamelan logam dipukul 🔔', ['gong', 'bonang', 'saron']]] },
  { c: 'tebakjajanan', n: '🍡 Tebak Jajanan', d: 'Tebak jajanan Indonesia', hadiah: 350, exp: 45, bank: [['Bola aci digoreng, kopong 🟤', 'cimol'], ['Aci dicolok bumbu kacang 🍢', 'cilok'], ['Makaroni pedas kering 🌶️', ['makaroni', 'maklor']], ['Tahu bulat digoreng dadakan 🟡', ['tahu bulat', 'tahubulat']], ['Pisang goreng + coklat keju 🍌', ['pisang coklat', 'piscok']], ['Martabak mini manis 🥞', ['terang bulan', 'martabak']], ['Es serut + susu + sirup 🍧', ['es campur', 'escampur']], ['Kue cubit motif laba-laba 🕸️', ['kue cubit', 'kuecubit']]] },
  { c: 'tebakminuman', n: '🥤 Tebak Minuman', d: 'Tebak minuman segar', hadiah: 350, exp: 45, bank: [['Kopi + susu + gula aren 🧋', ['kopi susu', 'es kopi']], ['Teh manis dingin 🍵', ['es teh', 'esteh']], ['Susu fermentasi asam 🥛', ['yakult', 'yogurt', 'yoghurt']], ['Kelapa muda utuh 🥥', ['es kelapa', 'degan', 'kelapa']], ['Jahe hangat + susu 🫚', ['stmj', 'susu jahe', 'wedang']], ['Alpukat + coklat 🥑', ['jus alpukat', 'es alpukat']], ['Cincau + santan + gula merah ⬛', ['es cincau', 'escincau']], ['Jeruk peras murni 🍊', ['es jeruk', 'jus jeruk']]] },
  { c: 'tebaksayur', n: '🥬 Tebak Sayur', d: 'Tebak sayuran', hadiah: 300, exp: 40, bank: [['Hijau, Popeye suka 💪', ['bayam', 'spinach']], ['Oranye, baik untuk mata 🥕', 'wortel'], ['Bulat, bikin nangis 🧅', ['bawang bombay', 'bombay']], ['Ungu panjang 🍆', 'terong'], ['Hijau keriting untuk lalapan 🥗', ['selada', 'lettuce']], ['Kecil hijau dalam polong 🫛', ['kacang polong', 'ercis']], ['Besar oranye khas Halloween 🎃', ['labu', 'pumpkin']], ['Putih seperti bunga kecil 🥦', ['kembang kol', 'brokoli']]] },
  { c: 'tebakbunga', n: '🌸 Tebak Bunga', d: 'Tebak bunga cantik', hadiah: 300, exp: 40, bank: [['Merah, simbol cinta 🌹', 'mawar'], ['Putih harum untuk tabur ⚪', ['melati', 'jasmine']], ['Kuning besar ikut matahari 🌻', ['bunga matahari', 'matahari', 'sunflower']], ['Raksasa bau busuk 🤢', ['raflesia', 'bangkai']], ['Hias eksotis Indonesia 🦋', 'anggrek'], ['Mekar pagi hari 🌅', ['pukul delapan', 'krokot']], ['Sakura Indonesia, pink 🌸', ['tabebuya', 'sakura']], ['Tulip Belanda? Bukan! Merah putih 🇮🇩', ['tulip', 'sepatu']]] },
  { c: 'tebaktanaman', n: '🌿 Tebak Tanaman', d: 'Tebak tanaman & pohon', hadiah: 300, exp: 40, bank: [['Daun dimasak + santan 🌱', ['daun singkong', 'singkong']], ['Pohon tinggi buah berserat 🌴', ['kelapa', 'nyiur']], ['Berduri, buah para raja 👑', 'durian'], ['Merambat, buah asam segar 🍇', 'anggur'], ['Herbal rimpang kuning 🫚', ['kunyit', 'turmeric']], ['Pohon besar rindang 🌳', 'beringin'], ['Ruas-ruas tinggi 🎋', 'bambu'], ['Berdaun tebal berduri 🌵', 'kaktus']] },
  { c: 'tebakburung', n: '🦅 Tebak Burung', d: 'Tebak burung', hadiah: 350, exp: 45, bank: [['Tidak bisa terbang, hidup di kutub 🐧', ['pinguin', 'penguin']], ['Besar merah muda, leher panjang 🦩', 'flamingo'], ['Pintar meniru bicara 🦜', ['beo', 'kakatua', 'parrot']], ['Lambang negara Indonesia 🦅', 'garuda'], ['Berburu di malam hari 🦉', ['burung hantu', 'hantu', 'owl']], ['Kecil bunyi "kuk-kuk" 🐦', ['perkutut', 'tekukur']], ['Ekor indah bisa mekar 🦚', 'merak'], ['Kecil penghisap madu 🌺', ['kolibri', 'hummingbird']]] },
  { c: 'tebakikan', n: '🐟 Tebak Ikan', d: 'Tebak ikan laut & tawar', hadiah: 350, exp: 45, bank: [['Gigi tajam, predator laut 🦈', ['hiu', 'shark']], ['Bisa menggelembung 🐡', ['buntal', 'puffer']], ['Bisa menyetrum! ⚡', ['belut listrik', 'belut', 'sidat']], ['Hias mahal Asia 🐉', 'arwana'], ['Kecil oranye, sahabat Dory 🐠', ['nemo', 'badut', 'clownfish']], ['Raksasa air tawar Amazon 🐋', ['arapaima', 'paiche']], ['Bisa "terbang" di atas laut 🕊️', ['ikan terbang', 'terbang']], ['Hias Jepang mahal 🎏', 'koi']] },
  { c: 'tebakserangga', n: '🐛 Tebak Serangga', d: 'Tebak serangga kecil', hadiah: 300, exp: 40, bank: [['Kupu-kupu malam 🌙', ['ngengat', 'moth']], ['Bokong bercahaya ✨', ['kunang-kunang', 'kunang']], ['Penghasil madu 🍯', ['lebah', 'bee']], ['Penghisap darah gatal 🩸', 'nyamuk'], ['Jago melompat 🦗', ['belalang', 'jangkrik']], ['Bau, suka di got 🪳', ['kecoak', 'lipas']], ['Kumbang bertanduk 🪲', ['kumbang', 'beetle']], ['Bersayap bening pemburu 🪰', ['capung', 'dragonfly']]] },
  { c: 'tebakdino', n: '🦕 Tebak Dino', d: 'Tebak dinosaurus', hadiah: 400, exp: 50, bank: [['Leher super panjang 🦕', ['brachiosaurus', 'bronto']], ['Raja kadal tiran 👑', ['t-rex', 'tyrannosaurus', 'trex']], ['Tanduk tiga di wajah 🦏', 'triceratops'], ['Berlayar di punggung ⛵', 'spinosaurus'], ['Cepat, cakar sabit 🪝', 'velociraptor'], ['Berzirah + gada ekor 🛡️', 'ankylosaurus'], ['Reptil terbang purba 🕊️', ['pterodactyl', 'pteranodon']], ['Kecil seukuran ayam 🐔', ['compsognathus', 'compie']]] },
  { c: 'tebakplanet', n: '🪐 Tebak Planet', d: 'Tebak planet tata surya', hadiah: 300, exp: 40, bank: [['Bercincin indah 💍', 'saturnus'], ['Merah, planet ke-4 🔴', 'mars'], ['Terbesar, bintik merah 🌀', 'jupiter'], ['Paling panas, dekat matahari ☀️', 'merkurius'], ['Bintang kejora 🌟', 'venus'], ['Raksasa es miring 🧊', 'uranus'], ['Paling jauh, biru tua 🌊', 'neptunus'], ['Rumah kita 🌍', 'bumi']] },
  { c: 'tebaksungai', n: '🌊 Tebak Sungai', d: 'Tebak sungai dunia', hadiah: 350, exp: 45, bank: [['Terpanjang di dunia 🗺️', ['nil', 'nile']], ['Terbesar di Amazon 🏞️', 'amazon'], ['Sungai Kuning China 🟡', ['huang he', 'kuning']], ['Sungai suci India 🛕', ['gangga', 'ganges']], ['Terpanjang Indonesia, Kalimantan 🟢', 'kapuas'], ['Bengawan... legendaris 🎶', ['bengawan solo', 'solo']], ['Membelah Palembang 🌉', 'musi'], ['Kaltim, habitat pesut 🐬', 'mahakam']] },
  { c: 'tebakcandi', n: '🛕 Tebak Candi', d: 'Tebak candi Nusantara', hadiah: 350, exp: 45, bank: [['Candi Buddha terbesar, Magelang 🗿', 'borobudur'], ['Candi Hindu megah 🕉️', 'prambanan'], ['Candi "Tikus" 🐀', ['candi tikus', 'tikus']], ['Candi Penataran ada di? ⛰️', ['blitar', 'penataran']], ['Dekat Borobudur 🙏', 'mendut'], ['Candi Jago di Tumpang 🏔️', 'jago'], ['Candi kembar Klaten 💕', 'plaosan'], ['Candi erotis Karanganyar 🌋', 'sukuh']] },
  { c: 'tebakpahlawan', n: '🎖️ Tebak Pahlawan', d: 'Tebak pahlawan nasional', hadiah: 350, exp: 45, bank: [['Emansipasi wanita, Jepara 👩', 'kartini'], ['Proklamator pertama 🇮🇩', 'soekarno'], ['Bapak Koperasi 🤝', 'hatta'], ['Panglima Besar, perang gerilya ⚔️', ['soedirman', 'sudirman']], ['Srikandi Aceh 🗡️', ['cut nyak dien', 'cutnyakdien']], ['Perang Jawa, Pangeran 🐎', 'diponegoro'], ['Bapak Pendidikan 📚', ['ki hajar dewantara', 'dewantara']], ['Jenderal G30S 🎖️', ['ahmad yani', 'yani']]] },
  { c: 'tebakpresiden', n: '🏛️ Tebak Presiden', d: 'Tebak presiden RI', hadiah: 300, exp: 40, bank: [['Presiden pertama 🇮🇩', 'soekarno'], ['Orde Baru 32 tahun 🏢', 'soeharto'], ['Bapak Teknologi ✈️', 'habibie'], ['Gus Dur 😎', ['gus dur', 'wahid']], ['Presiden wanita pertama 👩', 'megawati'], ['Demokrat, 2 periode 💙', ['sby', 'yudhoyono']], ['Blusukan 🧢', ['jokowi', 'joko widodo']], ['Presiden 2024 🦅', 'prabowo']] },
  { c: 'tebakkotadunia', n: '🌆 Tebak Kota Dunia', d: 'Tebak kota dunia', hadiah: 350, exp: 45, bank: [['Menara Eiffel 🗼', 'paris'], ['Big Ben 🕰️', 'london'], ['Patung Liberty 🗽', ['new york', 'newyork']], ['Neon + kuil 🇯🇵', ['tokyo', 'kyoto']], ['Tembok Besar 🇨🇳', 'beijing'], ['Piramida Giza 🏜️', ['kairo', 'cairo', 'giza']], ['Kincir angin 🌷', 'amsterdam'], ['Opera House 🐨', 'sydney']] },
  { c: 'tebaktarian', n: '💃 Tebak Tarian', d: 'Tebak tarian daerah', hadiah: 350, exp: 45, bank: [['Bali, api + teriakan "cak" 🔥', 'kecak'], ['Jawa, lembut anggun 👸', ['serimpi', 'gambyong']], ['Aceh, tepuk kompak 👏', 'saman'], ['Sumbar pakai piring 🍽️', ['tari piring', 'piring']], ['Papua, semangat perang 🗡️', ['yospan', 'perang']], ['Dayak, burung enggang 🦅', ['enggang', 'hudoq']], ['Betawi bertopeng 🎭', ['topeng', 'ronggeng']], ['Sunda, dinamis 🦚', ['jaipong', 'merak']]] },
  { c: 'tebaklagudaerah', n: '🎵 Tebak Lagu Daerah', d: 'Tebak lagu dari liriknya', hadiah: 350, exp: 45, bank: [['"Apuse kokon dao..." 🎶', 'apuse'], ['"Yamko Rambe Yamko" 🥁', 'yamko'], ['"Bubuy Bulan" 🌙', ['bubuy bulan', 'bubuy']], ['"Anging Mamiri" ⛵', ['anging mamiri', 'mamiri']], ['"Rasa Sayange" 🌴', ['rasa sayange', 'sayange']], ['"Manuk Dadali" 🦅', ['manuk dadali', 'dadali']], ['"Gundul-gundul Pacul" 👒', ['gundul pacul', 'gundul']], ['"Soleram" Anak Medan 🌙', 'soleram']] },
  { c: 'tebakatlet', n: '🏅 Tebak Atlet', d: 'Tebak atlet terkenal', hadiah: 400, exp: 50, bank: [['Ganda campuran "Owi" 🏸', ['owi', 'tontowi']], ['Manusia tercepat dunia ⚡', ['bolt', 'usain bolt']], ['Perenang 23 emas 🏊', 'phelps'], ['Tunggal putra "Jojo" 🥇', ['jojo', 'jonatan']], ['MotoGP "The Doctor" 🏍️', ['rossi', 'valentino']], ['F1 juara 7x 🏎️', ['hamilton', 'schumacher']], ['Petinju "Iron" 🥊', ['tyson', 'mike tyson']], ['Angkat besi emas putri 🏋️', ['windy', 'cantika']]] },
  { c: 'tebakdrakor', n: '📺 Tebak Drakor', d: 'Tebak drama Korea', hadiah: 350, exp: 45, bank: [['Permainan cumi berhadiah 🦑', ['squid game', 'squidgame']], ['Zombie di sekolah 🧟', ['all of us are dead', 'allofus']], ['Goblin + pedang + 900 tahun ⚔️', 'goblin'], ['Wanita nyasar ke Korut 🪂', ['crash landing on you', 'cloy']], ['Pengacara autis pecinta paus 🐋', ['extraordinary attorney woo', 'woo young woo']], ['Hotel untuk arwah 🌙', ['hotel del luna', 'del luna']], ['Mafia Italia jadi pengacara 🇮🇹', 'vincenzo'], ['Keluarga superpower 💪', 'moving']] },
  /* ===== 20 KUIS ===== */
  { c: 'kuisplanet', n: '🪐 Kuis Planet', d: 'Kuis tata surya', hadiah: 300, exp: 40, bank: [['Planet yang bercincin?', 'saturnus'], ['Planet merah?', 'mars'], ['Planet terbesar?', 'jupiter'], ['Planet terdekat matahari?', 'merkurius'], ['Satelit alami bumi?', 'bulan'], ['Bintang terdekat bumi?', 'matahari']] },
  { c: 'kuisdino', n: '🦕 Kuis Dino', d: 'Kuis dinosaurus', hadiah: 350, exp: 45, bank: [['Raja dinosaurus?', ['t-rex', 'tyrannosaurus', 'trex']], ['Dino bertanduk tiga?', 'triceratops'], ['Dino leher panjang?', ['brachiosaurus', 'bronto']], ['Dino tercepat pemburu?', 'velociraptor'], ['Reptil terbang purba?', ['pterodactyl', 'pteranodon']], ['Dino punggung berlayar?', 'spinosaurus']] },
  { c: 'kuisbenua', n: '🌍 Kuis Benua', d: 'Kuis benua dunia', hadiah: 300, exp: 40, bank: [['Benua terluas?', 'asia'], ['Benua terkecil?', 'australia'], ['Gurun Sahara ada di benua?', 'afrika'], ['Sungai Amazon di benua?', ['amerika', 'amerika selatan']], ['Benua es di kutub selatan?', 'antartika'], ['Menara Eiffel di benua?', 'eropa']] },
  { c: 'kuissungai', n: '🌊 Kuis Sungai', d: 'Kuis sungai', hadiah: 300, exp: 40, bank: [['Sungai terpanjang di dunia?', ['nil', 'nile']], ['Sungai terpanjang di Indonesia?', 'kapuas'], ['Sungai yang membelah Palembang?', 'musi'], ['Bengawan ... (Solo)?', 'solo'], ['Sungai Kuning di China?', ['huang he', 'kuning']], ['Sungai suci di India?', ['gangga', 'ganges']]] },
  { c: 'kuiscandi', n: '🛕 Kuis Candi', d: 'Kuis candi', hadiah: 300, exp: 40, bank: [['Candi Buddha terbesar di dunia?', 'borobudur'], ['Candi Hindu terbesar di Indonesia?', 'prambanan'], ['Candi Penataran ada di kota?', 'blitar'], ['Candi Tikus ada di daerah?', ['mojokerto', 'trowulan']], ['Candi yang dekat Borobudur?', 'mendut'], ['Candi Sukuh ada di?', 'karanganyar']] },
  { c: 'kuispahlawan', n: '🎖️ Kuis Pahlawan', d: 'Kuis pahlawan', hadiah: 300, exp: 40, bank: [['Pahlawan emansipasi wanita?', 'kartini'], ['Proklamator kemerdekaan?', 'soekarno'], ['Panglima Besar TNI?', ['soedirman', 'sudirman']], ['Bapak Koperasi Indonesia?', 'hatta'], ['Cut Nyak Dien berasal dari?', 'aceh'], ['Pangeran ... (Perang Jawa)?', 'diponegoro']] },
  { c: 'kuispresiden', n: '🏛️ Kuis Presiden', d: 'Kuis presiden RI', hadiah: 250, exp: 35, bank: [['Presiden pertama RI?', 'soekarno'], ['Presiden ke-7 RI?', 'jokowi'], ['Presiden wanita pertama?', 'megawati'], ['Julukan B.J. Habibie?', ['bapak teknologi', 'teknologi']], ['Presiden RI tahun 2024?', 'prabowo'], ['Wakil presiden pertama?', 'hatta']] },
  { c: 'kuiskotadunia', n: '🌆 Kuis Kota Dunia', d: 'Kuis ibukota dunia', hadiah: 300, exp: 40, bank: [['Ibukota Jepang?', 'tokyo'], ['Ibukota Prancis?', 'paris'], ['Ibukota Inggris?', 'london'], ['Ibukota Mesir?', ['kairo', 'cairo']], ['Ibukota Australia?', 'canberra'], ['Ibukota Korea Selatan?', 'seoul']] },
  { c: 'kuistarian', n: '💃 Kuis Tarian', d: 'Kuis tarian daerah', hadiah: 300, exp: 40, bank: [['Tari api dari Bali?', 'kecak'], ['Tari Piring berasal dari?', ['minang', 'padang', 'sumbar']], ['Tari Saman berasal dari?', ['aceh', 'gayo']], ['Tari perang khas Papua?', 'yospan'], ['Tari Jaipong berasal dari?', ['sunda', 'jabar', 'jawabarat']], ['Tari Topeng khas?', ['betawi', 'jakarta']]] },
  { c: 'kuislagudaerah', n: '🎵 Kuis Lagu Daerah', d: 'Kuis asal lagu daerah', hadiah: 300, exp: 40, bank: [['Lagu "Apuse" berasal dari?', 'papua'], ['Lagu "Yamko Rambe Yamko" dari?', 'papua'], ['Lagu "Bubuy Bulan" dari?', ['sunda', 'jawabarat']], ['Lagu "Rasa Sayange" dari?', ['maluku', 'ambon']], ['Lagu "Gundul Pacul" dari?', ['jawa', 'jateng']], ['Lagu "Anging Mamiri" dari?', ['makassar', 'bugis']]] },
  { c: 'kuisalatmusik', n: '🎺 Kuis Alat Musik', d: 'Kuis alat musik', hadiah: 300, exp: 40, bank: [['Alat musik petik 6 senar?', 'gitar'], ['Alat musik tiup dari bambu khas Sunda?', ['suling', 'seruling']], ['Alat musik gesek 4 senar?', 'biola'], ['Gamelan besar yang dipukul?', 'gong'], ['Alat musik pukul dari kulit?', ['gendang', 'drum']], ['Alat musik tuts hitam putih?', ['piano', 'pianika']]] },
  { c: 'kuisjajanan', n: '🍡 Kuis Jajanan', d: 'Kuis jajanan', hadiah: 300, exp: 40, bank: [['Bola aci kopong digoreng?', 'cimol'], ['Aci tusuk bumbu kacang?', 'cilok'], ['Pisang goreng coklat keju?', ['piscok', 'pisang coklat']], ['Kue motif laba-laba?', ['kue cubit', 'cubit']], ['Es serut susu + sirup?', ['es campur', 'campur']], ['Martabak mini manis?', ['terang bulan', 'martabak']]] },
  { c: 'kuisvitamin', n: '🍊 Kuis Vitamin', d: 'Kuis gizi & vitamin', hadiah: 300, exp: 40, bank: [['Vitamin untuk kesehatan mata?', ['a', 'vitamin a']], ['Vitamin dari sinar matahari?', ['d', 'vitamin d']], ['Vitamin untuk daya tahan tubuh?', ['c', 'vitamin c']], ['Buah kaya vitamin C?', ['jeruk', 'jambu']], ['Vitamin pembekuan darah?', ['k', 'vitamin k']], ['Kekurangan zat besi menyebabkan?', 'anemia']] },
  { c: 'kuisatlet', n: '🏅 Kuis Atlet', d: 'Kuis atlet', hadiah: 350, exp: 45, bank: [['Atlet lari tercepat dunia?', ['bolt', 'usain bolt']], ['Perenang 23 medali emas?', 'phelps'], ['Julukan Valentino Rossi?', ['the doctor', 'doctor']], ['Pasangan Liliyana (Owi)?', ['tontowi', 'owi']], ['Tunggal putra "Jojo"?', ['jonatan', 'jojo']], ['Petinju "Iron Mike"?', ['tyson', 'mike tyson']]] },
  { c: 'kuisdrakor', n: '📺 Kuis Drakor', d: 'Kuis drama Korea', hadiah: 300, exp: 40, bank: [['Drama permainan cumi?', ['squid game', 'squidgame']], ['Drama zombie di sekolah?', ['all of us are dead', 'allofus']], ['Drama pengacara pecinta paus?', ['woo young woo', 'extraordinary']], ['Drama hotel untuk arwah?', ['hotel del luna', 'del luna']], ['Drama pengacara mafia Italia?', 'vincenzo'], ['Aktor utama Goblin?', ['gong yoo', 'gongyoo']]] },
  { c: 'kuisanime', n: '⛩️ Kuis Anime', d: 'Kuis anime Jepang', hadiah: 300, exp: 40, bank: [['Ninja desa Konoha?', 'naruto'], ['Bajak laut topi jerami?', 'luffy'], ['Pembasmi iblis Tanjiro?', ['demon slayer', 'kimetsu']], ['Eren vs Titan?', ['attack on titan', 'aot']], ['Bola naga Goku?', ['dragon ball', 'goku']], ['Detektif cilik?', ['conan', 'detektif conan']]] },
  { c: 'kuisvideogame', n: '🎮 Kuis Video Game', d: 'Kuis dunia game', hadiah: 300, exp: 40, bank: [['Tukang ledeng Italia topi merah?', 'mario'], ['Battle royale "Winner Winner"?', 'pubg'], ['Game balok membangun dunia?', 'minecraft'], ['MOBA analog 5v5?', ['mobile legends', 'ml']], ['Kuning makan titik di labirin?', 'pacman'], ['Petualang topi hijau?', ['zelda', 'link']]] },
  { c: 'kuisburung', n: '🦅 Kuis Burung', d: 'Kuis burung', hadiah: 300, exp: 40, bank: [['Burung tak bisa terbang di kutub?', ['pinguin', 'penguin']], ['Burung lambang negara RI?', 'garuda'], ['Burung aktif di malam hari?', ['burung hantu', 'hantu', 'owl']], ['Burung pintar meniru bicara?', 'beo'], ['Burung berekor indah?', 'merak'], ['Burung tercepat saat menukik?', ['alap-alap', 'falcon']]] },
  { c: 'kuisikan', n: '🐟 Kuis Ikan', d: 'Kuis ikan', hadiah: 300, exp: 40, bank: [['Ikan predator bergigi tajam?', ['hiu', 'shark']], ['Ikan hias "naga" Asia?', 'arwana'], ['Ikan yang bisa menyetrum?', ['belut listrik', 'belut', 'sidat']], ['Ikan badut oranye?', ['nemo', 'badut']], ['Ikan koi berasal dari?', 'jepang'], ['Ikan yang bisa menggelembung?', ['buntal', 'puffer']]] },
  { c: 'kuisserangga', n: '🐛 Kuis Serangga', d: 'Kuis serangga', hadiah: 300, exp: 40, bank: [['Serangga penghasil madu?', 'lebah'], ['Serangga bokong bercahaya?', ['kunang-kunang', 'kunang']], ['Sebutan kupu-kupu malam?', ['ngengat', 'moth']], ['Serangga penghisap darah?', 'nyamuk'], ['Serangga jago melompat?', ['belalang', 'jangkrik']], ['Serangga bau di got?', ['kecoak', 'lipas']]] },
  /* ===== 10 MATEMATIKA ===== */
  { c: 'tambahcepat', n: '➕ Tambah Cepat', d: 'Penjumlahan kilat', hadiah: 250, exp: 40, gen: GEN.tambah },
  { c: 'kurangcepat', n: '➖ Kurang Cepat', d: 'Pengurangan kilat', hadiah: 250, exp: 40, gen: GEN.kurang },
  { c: 'kalicepat', n: '✖️ Kali Cepat', d: 'Perkalian kilat', hadiah: 250, exp: 40, gen: GEN.kali },
  { c: 'bagicepat', n: '➗ Bagi Cepat', d: 'Pembagian kilat', hadiah: 250, exp: 40, gen: GEN.bagi },
  { c: 'pangkatcepat', n: '🟪 Pangkat Cepat', d: 'Kuadrat kilat', hadiah: 300, exp: 45, gen: GEN.pangkat },
  { c: 'akarkuadrat', n: '√ Akar Kuadrat', d: 'Akar kuadrat kilat', hadiah: 300, exp: 45, gen: GEN.akar },
  { c: 'pecahancepat', n: '🍰 Pecahan Cepat', d: 'Jumlah pecahan (x/y)', hadiah: 350, exp: 50, gen: GEN.pecahan },
  { c: 'persencepat', n: '💯 Persen Cepat', d: 'Hitung persen kilat', hadiah: 300, exp: 45, gen: GEN.persen },
  { c: 'tebakpola', n: '🔢 Tebak Pola', d: 'Lanjutkan pola angka', hadiah: 350, exp: 50, gen: GEN.pola },
  { c: 'suhucepat', n: '🌡️ Suhu Cepat', d: 'Konversi °C ke °F', hadiah: 300, exp: 45, gen: GEN.suhu },
  /* ===== 10 KATA ===== */
  { c: 'sinonimcepat', n: '📖 Sinonim Cepat', d: 'Tebak persamaan kata', hadiah: 300, exp: 40, bank: [['Persamaan kata BAHAGIA?', ['senang', 'gembira', 'riang']], ['Persamaan kata SEDIH?', ['duka', 'murung', 'pilu']], ['Persamaan kata CEPAT?', ['sigap', 'gesit', 'lekas']], ['Persamaan kata INDAH?', ['cantik', 'elok', 'molek']], ['Persamaan kata BESAR?', ['agung', 'raksasa', 'jumbo']], ['Persamaan kata KECIL?', ['mini', 'mungil', 'cilik']], ['Persamaan kata PINTAR?', ['cerdas', 'brilian']], ['Persamaan kata KUAT?', ['kokoh', 'tangguh']]] },
  { c: 'tebakantonim', n: '🔄 Tebak Antonim', d: 'Tebak lawan kata', hadiah: 300, exp: 40, bank: [['Lawan kata PANAS?', 'dingin'], ['Lawan kata TINGGI?', ['rendah', 'pendek']], ['Lawan kata KAYA?', 'miskin'], ['Lawan kata CEPAT?', 'lambat'], ['Lawan kata TERANG?', 'gelap'], ['Lawan kata BAIK?', 'jahat'], ['Lawan kata BESAR?', 'kecil'], ['Lawan kata RAJIN?', 'malas']] },
  { c: 'acakkalimat', n: '🔀 Acak Kalimat', d: 'Susun kata jadi kalimat', hadiah: 350, exp: 45, gen: GEN.acakkalimat },
  { c: 'tebakistilah', n: '💡 Tebak Istilah', d: 'Tebak istilah teknologi', hadiah: 350, exp: 45, bank: [['Julukan "otak komputer"?', ['cpu', 'prosesor']], ['Jaringan komputer global?', 'internet'], ['Singkatan kecerdasan buatan?', ['ai', 'artificial intelligence']], ['Mata uang digital?', ['kripto', 'bitcoin', 'crypto']], ['Robot penjawab chat?', ['chatbot', 'bot']], ['Program jahat perusak?', ['malware', 'virus']]] },
  { c: 'tebaksandi', n: '🕵️ Tebak Sandi', d: 'Pecahkan sandi geser', hadiah: 400, exp: 50, gen: GEN.sandi },
  { c: 'sandiangka', n: '🔢 Sandi Angka', d: 'Pecahkan sandi A1Z26', hadiah: 400, exp: 50, gen: GEN.sandiangka },
  { c: 'tebakmotto', n: '📜 Tebak Motto', d: 'Tebak semboyan & slogan', hadiah: 350, exp: 45, bank: [['Semboyan negara Indonesia?', ['bhinneka tunggal ika', 'bhinneka']], ['"Tut Wuri Handayani" milik dunia?', ['pendidikan', 'ki hajar']], ['Slogan "Just Do It" milik?', 'nike'], ['Slogan "Think Different" milik?', 'apple'], ['Slogan "I\'m Lovin\' It" milik?', ['mcd', 'mcdonald']], ['Semboyan "Bersatu teguh"?', ['pramuka', 'bersatu']]] },
  { c: 'tebakiklan', n: '📺 Tebak Iklan', d: 'Tebak merek dari slogan', hadiah: 350, exp: 45, bank: [['Slogan "Seleraku"?', 'indomie'], ['"Apapun makanannya..."?', ['teh botol', 'sosro']], ['"Sampai tetes terakhir"?', ['kecap bango', 'bango']], ['Shampo anti ketombe legendaris?', ['head shoulders', 'clear']], ['Teh melati dalam kemasan?', ['sariwangi', '2tang', 'duatang']], ['Pasta gigi merah putih?', ['pepsodent', 'ciptadent']]] },
  { c: 'tebakpenyanyi', n: '🎤 Tebak Penyanyi', d: 'Tebak penyanyi lagu hits', hadiah: 350, exp: 45, bank: [['Penyanyi "Laskar Pelangi"?', ['nidji', 'giring']], ['Penyanyi "Separuh Aku"?', 'noah'], ['Raja dangdut Indonesia?', ['rhoma', 'rhoma irama']], ['Penyanyi "Begadang"?', ['rhoma', 'rhoma irama']], ['Diva lagu "Hati Yang Kau Sakiti"?', ['rossa', 'rossa']], ['Band lagu "Kangen"?', ['dewa', 'dewa 19']]] },
  { c: 'tebakbandara', n: '✈️ Tebak Bandara', d: 'Tebak kode bandara', hadiah: 350, exp: 45, bank: [['Kode bandara CGK?', ['jakarta', 'soekarno hatta']], ['Kode bandara DPS?', ['bali', 'ngurah rai']], ['Kode bandara SUB?', 'surabaya'], ['Kode bandara JOG?', ['yogya', 'yogyakarta']], ['Kode bandara SIN?', ['singapura', 'singapore']], ['Kode bandara KUL?', ['kuala lumpur', 'malaysia']]] }
]

void acakHuruf
export default DAFTAR.map(buat)
