/**
 * ✨ v7.9.0 BATCH C — 10 fitur baru × 5 kategori (Info · Downloader · Internet · Islami · Main Menu)
 * ------------------------------------------------------------------------------
 *  Info      : API publik gratis tanpa key (BMKG gempa, wiki, open-meteo, dsb.)
 *  Downloader: sumber generik lewat yt-dlp (Facebook, Twitter/X, Instagram
 *              reels, Threads, SoundCloud, Pinterest video, CapCut, Likee,
 *              Snack Video, Bilibili) + fallback pesan instalasi.
 *  Internet  : utilitas jaringan/web lokal & API publik.
 *  Islami    : kalkulator & referensi ibadah lokal (tanpa API).
 *  Main Menu : navigasi menu baru (cari, acak, favorit, terbaru, ...).
 */
import fs from 'node:fs'
import path from 'node:path'
import { spawn } from 'node:child_process'
import { config } from '../config.js'
import { ROOT, truncate, formatSize, formatDuration, getJSON, pickRandom } from '../lib/functions.js'
import { getUser, saveDB, getStats, getSettings } from '../lib/database.js'
import { listPlugins, categories } from '../lib/plugins.js'

const P = config.display.prefix
const K = m => m.senderKey || m.sender
const UA = 'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Mobile Safari/537.36'
const plug = (cat, command, aliases, description, run, opt = {}) => ({
  command: [command, ...aliases], category: cat, description, limit: 1, cooldown: 3, ...opt,
  run: async (m, ctx) => { try { return await run(m, ctx) } catch (e) { return m.reply(`⚠️ ${truncate(String(e.message || e), 220)}`) } }
})
async function json (url, timeout = 20000) {
  const r = await fetch(url, { redirect: 'follow', signal: AbortSignal.timeout(timeout), headers: { 'User-Agent': UA, Accept: 'application/json' } })
  if (!r.ok) throw new Error(`HTTP ${r.status}`)
  return await r.json()
}
const urlDari = m => (m.q || '').match(/https?:\/\/[^\s]+/i)?.[0] || ''

/* ================================================================== */
/*  1. INFO MENU — 10 fitur                                             */
/* ================================================================== */
export const INFO_BARU = [
  plug('Info Menu', 'gempa', ['gempaterkini', 'bmkg', 'infogempa'], '🌋 Gempa terkini dari BMKG (magnitudo, lokasi, kedalaman, potensi tsunami)', async m => { const d = await json('https://data.bmkg.go.id/DataMKG/TEWS/autogempa.json'); const g = d?.Infogempa?.gempa; if (!g) throw new Error('data BMKG kosong'); return m.reply(`🌋 *GEMPA TERKINI — BMKG*\n\n📅 ${g.Tanggal} · ${g.Jam}\n📍 ${g.Wilayah}\n\n▸ Magnitudo: *M ${g.Magnitude}*\n▸ Kedalaman: ${g.Kedalaman}\n▸ Koordinat: ${g.Coordinates}\n▸ Potensi: ${g.Potensi}\n${g.Dirasakan ? `▸ Dirasakan: ${g.Dirasakan}` : ''}\n\nSumber: data.bmkg.go.id`) }),
  plug('Info Menu', 'gempaterbaru15', ['daftargempa', 'gempa15', 'gempadirasakan'], '🌋 15 gempa terbaru M≥5 dari BMKG', async m => { const d = await json('https://data.bmkg.go.id/DataMKG/TEWS/gempaterkini.json'); const list = d?.Infogempa?.gempa || []; return m.reply(`🌋 *15 GEMPA TERBARU (M≥5) — BMKG*\n\n${list.slice(0, 15).map((g, i) => `${i + 1}. *M${g.Magnitude}* ${g.Tanggal} ${g.Jam}\n   ${truncate(g.Wilayah, 60)} · ${g.Kedalaman}`).join('\n')}`) }),
  plug('Info Menu', 'wikiringkas', ['ringkasanwiki', 'cariwiki', 'ensiklopedia'], '📚 Ringkasan Wikipedia Indonesia (fallback EN): .wiki Soekarno', async m => { if (!m.q) return m.reply(`📚 \`${P}wikiringkas Soekarno\``); let d; try { d = await json(`https://id.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(m.q)}`) } catch { d = await json(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(m.q)}`) } if (!d?.extract) throw new Error('tidak ditemukan'); const teks = `📚 *${d.title}*${d.description ? `\n_${d.description}_` : ''}\n\n${truncate(d.extract, 1500)}\n\n🔗 ${d.content_urls?.mobile?.page || d.content_urls?.desktop?.page || ''}`; if (d.thumbnail?.source) { try { return await m.sendImage(d.thumbnail.source, teks) } catch {} } return m.reply(teks) }),
  plug('Info Menu', 'cuacajam', ['prakiraan', 'cuacaperjam', 'ramalancuaca'], '🌦️ Prakiraan cuaca per 3 jam (24 jam ke depan) + suhu maks/min 3 hari (Open-Meteo): .cuacajam Medan', async m => { const kota = m.q || 'Medan'; const g = await json(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(kota)}&count=1&language=id`); const l = g?.results?.[0]; if (!l) throw new Error('kota tidak ditemukan'); const w = await json(`https://api.open-meteo.com/v1/forecast?latitude=${l.latitude}&longitude=${l.longitude}&hourly=temperature_2m,precipitation_probability,weather_code&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto&forecast_days=3`); const ikon = c => c === 0 ? '☀️' : c <= 3 ? '⛅' : c <= 48 ? '🌫️' : c <= 67 ? '🌧️' : c <= 77 ? '🌨️' : c <= 82 ? '🌦️' : '⛈️'; const now = new Date().getHours(); const jam = w.hourly.time.map((t, i) => ({ t, i })).filter(({ t }) => new Date(t).getHours() % 3 === 0 && i >= now - now % 3).slice(0, 8); return m.reply(`🌦️ *PRAKIRAAN ${l.name.toUpperCase()}${l.admin1 ? ', ' + l.admin1 : ''}*\n\n${jam.map(({ t, i }) => `${String(new Date(t).getHours()).padStart(2, '0')}:00 ${ikon(w.hourly.weather_code[i])} ${w.hourly.temperature_2m[i]}°C · hujan ${w.hourly.precipitation_probability[i]}%`).join('\n')}\n\n*3 hari:*\n${w.daily.time.map((t, i) => `${new Date(t).toLocaleDateString('id-ID', { weekday: 'short' })}: ${w.daily.temperature_2m_min[i]}–${w.daily.temperature_2m_max[i]}°C · hujan ${w.daily.precipitation_probability_max[i]}%`).join('\n')}`) }),
  plug('Info Menu', 'kualitasudara', ['aqi', 'polusi', 'udara'], '😷 Indeks kualitas udara (PM2.5, PM10, AQI) suatu kota — Open-Meteo Air Quality', async m => { const kota = m.q || 'Medan'; const g = await json(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(kota)}&count=1&language=id`); const l = g?.results?.[0]; if (!l) throw new Error('kota tidak ditemukan'); const a = await json(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${l.latitude}&longitude=${l.longitude}&current=pm10,pm2_5,carbon_monoxide,ozone,us_aqi`); const c = a.current; const lvl = c.us_aqi <= 50 ? '🟢 Baik' : c.us_aqi <= 100 ? '🟡 Sedang' : c.us_aqi <= 150 ? '🟠 Tidak sehat (sensitif)' : c.us_aqi <= 200 ? '🔴 Tidak sehat' : '🟣 Sangat tidak sehat'; return m.reply(`😷 *KUALITAS UDARA ${l.name.toUpperCase()}*\n\n▸ AQI (US): *${c.us_aqi}* — ${lvl}\n▸ PM2.5: ${c.pm2_5} µg/m³\n▸ PM10: ${c.pm10} µg/m³\n▸ CO: ${c.carbon_monoxide} µg/m³\n▸ Ozon: ${c.ozone} µg/m³\n\n${c.us_aqi > 100 ? '💡 Pakai masker & kurangi aktivitas luar ruangan.' : '💡 Aman untuk aktivitas luar.'}`) }),
  plug('Info Menu', 'kripto', ['crypto', 'hargakripto', 'btc'], '🪙 Harga kripto realtime dalam IDR & USD + perubahan 24 jam (CoinGecko): .kripto bitcoin ethereum', async m => { const ids = (m.q || 'bitcoin ethereum solana').toLowerCase().split(/[\s,]+/).slice(0, 8).join(','); const d = await json(`https://api.coingecko.com/api/v3/simple/price?ids=${ids}&vs_currencies=idr,usd&include_24hr_change=true`); const rows = Object.entries(d); if (!rows.length) throw new Error('koin tidak ditemukan (pakai id: bitcoin, ethereum, solana, dogecoin, ...)'); return m.reply(`🪙 *HARGA KRIPTO*\n\n${rows.map(([k, v]) => `*${k}*\n  Rp ${Math.round(v.idr).toLocaleString('id-ID')} · $${v.usd.toLocaleString('en-US')} · ${v.idr_24h_change >= 0 ? '📈 +' : '📉 '}${(v.idr_24h_change || 0).toFixed(2)}%`).join('\n')}\n\nSumber: CoinGecko`) }),
  plug('Info Menu', 'hargaemas', ['emas', 'goldprice', 'hargaperak'], '🥇 Harga emas & perak per gram (IDR) dari kurs XAU/XAG', async m => { const d = await json('https://api.exchangerate-api.com/v4/latest/XAU').catch(() => null); let idrPerOz = d?.rates?.IDR; if (!idrPerOz) { const g = await json('https://api.coingecko.com/api/v3/simple/price?ids=pax-gold&vs_currencies=idr'); idrPerOz = g['pax-gold'].idr } const gram = idrPerOz / 31.1035; return m.reply(`🥇 *HARGA EMAS HARI INI*\n\n▸ 1 gram: *Rp ${Math.round(gram).toLocaleString('id-ID')}*\n▸ 5 gram: Rp ${Math.round(gram * 5).toLocaleString('id-ID')}\n▸ 10 gram: Rp ${Math.round(gram * 10).toLocaleString('id-ID')}\n▸ 1 troy oz: Rp ${Math.round(idrPerOz).toLocaleString('id-ID')}\n\n_Harga spot dunia; harga toko/Antam biasanya lebih tinggi 5-10%._\n💡 Hitung zakat: ${P}kalkzakatmal`) }),
  plug('Info Menu', 'profilnegara', ['negarainfo', 'datanegara', 'faktanegara'], '🌍 Info negara: ibu kota, populasi, mata uang, bahasa, zona waktu, bendera (REST Countries): .negara Jepang', async m => { if (!m.q) return m.reply(`🌍 \`${P}profilnegara Jepang\``); const d = await json(`https://restcountries.com/v3.1/translation/${encodeURIComponent(m.q)}?fields=name,capital,population,currencies,languages,timezones,flags,region,subregion,area,translations`).catch(() => json(`https://restcountries.com/v3.1/name/${encodeURIComponent(m.q)}?fields=name,capital,population,currencies,languages,timezones,flags,region,subregion,area,translations`)); const c = Array.isArray(d) ? d[0] : d; if (!c) throw new Error('negara tidak ditemukan'); const teks = `🌍 *${c.translations?.ind?.common || c.name.common}* (${c.name.official})\n\n▸ Ibu kota: ${(c.capital || []).join(', ') || '-'}\n▸ Wilayah: ${c.region} · ${c.subregion || ''}\n▸ Populasi: ${c.population.toLocaleString('id-ID')} jiwa\n▸ Luas: ${c.area.toLocaleString('id-ID')} km²\n▸ Mata uang: ${Object.values(c.currencies || {}).map(v => `${v.name} (${v.symbol || ''})`).join(', ')}\n▸ Bahasa: ${Object.values(c.languages || {}).join(', ')}\n▸ Zona waktu: ${c.timezones.slice(0, 4).join(', ')}`; try { return await m.sendImage(c.flags.png, teks) } catch { return m.reply(teks) } }),
  plug('Info Menu', 'hariini2', ['padaharini', 'sejarahhariini', 'onthisday'], '📅 Peristiwa sejarah dunia pada tanggal hari ini (Wikipedia On This Day)', async m => { const now = new Date(); const d = await json(`https://id.wikipedia.org/api/rest_v1/feed/onthisday/events/${now.getMonth() + 1}/${now.getDate()}`).catch(() => json(`https://en.wikipedia.org/api/rest_v1/feed/onthisday/events/${now.getMonth() + 1}/${now.getDate()}`)); const ev = (d.events || []).sort((a, b) => b.year - a.year).slice(0, 10); return m.reply(`📅 *PADA HARI INI (${now.getDate()}/${now.getMonth() + 1}) DALAM SEJARAH*\n\n${ev.map(e => `▸ *${e.year}* — ${truncate(e.text, 140)}`).join('\n')}`) }),
  plug('Info Menu', 'nomorpenting', ['daruratnomor', 'nomordarurat', 'callcenter'], '🆘 Daftar nomor darurat & layanan penting di Indonesia', m => m.reply(`🆘 *NOMOR DARURAT INDONESIA*\n\n▸ 112 — Panggilan darurat terpadu\n▸ 110 — Polisi\n▸ 113 / 1131 — Pemadam kebakaran\n▸ 118 / 119 — Ambulans & gawat darurat medis\n▸ 115 — Basarnas (SAR)\n▸ 129 — Posko bencana alam\n▸ 123 — PLN gangguan listrik\n▸ 108 — Informasi telepon\n▸ 1500-567 — Halo Kemkes\n▸ 119 ext 8 — Layanan kesehatan jiwa (SEJIWA)\n▸ 021-500454 — Komnas Perempuan\n▸ 129 / 1500-771 — Telepon Pelayanan Sosial Anak (TePSA)\n▸ 1500-000 — Kemenkumham / imigrasi\n▸ 1500-888 — Halo BPJS Kesehatan\n\n💡 Simpan nomor ini. Ketik \`${P}sholat\` untuk jadwal ibadah, \`${P}gempa\` untuk info BMKG.`), { limit: 0 })
]

/* ================================================================== */
/*  2. DOWNLOADER — 10 fitur (yt-dlp generik)                           */
/* ================================================================== */
function adaBinary (nama) { return new Promise(res => { const p = spawn('which', [nama]); let out = ''; p.stdout?.on('data', d => { out += d }); p.on('error', () => res(null)); p.on('close', c => res(c === 0 && out.trim() ? out.trim() : null)) }) }
async function ytDlp (args, batasMs = 180000) {
  const bin = await adaBinary('yt-dlp'); if (!bin) throw new Error('yt-dlp belum terpasang')
  return await new Promise((res, rej) => {
    const proc = spawn(bin, args, { cwd: path.join(ROOT, 'tmp') }); let err = ''
    const t = setTimeout(() => { try { proc.kill('SIGKILL') } catch {} rej(new Error('waktu habis (>3 menit)')) }, batasMs)
    proc.stderr?.on('data', d => { err += d }); proc.on('error', e => { clearTimeout(t); rej(e) })
    proc.on('close', code => { clearTimeout(t); code === 0 ? res(true) : rej(new Error(truncate(err.trim().split('\n').pop() || `exit ${code}`, 200))) })
  })
}
async function unduhGenerik (m, { url, audio = false, nama, maksMB = 60 }) {
  const id = 'dl' + Date.now().toString(36); const pola = path.join(ROOT, 'tmp', `${id}.%(ext)s`)
  try { fs.mkdirSync(path.join(ROOT, 'tmp'), { recursive: true }) } catch {}
  await m.react?.('⏳')
  const args = audio ? ['-x', '--audio-format', 'mp3', '--audio-quality', '5'] : ['-f', 'bv*[height<=720][ext=mp4]+ba[ext=m4a]/b[ext=mp4]/b', '--merge-output-format', 'mp4']
  await ytDlp([...args, '-o', pola, '--no-playlist', '--restrict-filenames', '--no-warnings', url])
  const file = fs.readdirSync(path.join(ROOT, 'tmp')).find(f => f.startsWith(id)); if (!file) throw new Error('file hasil tidak ditemukan')
  const full = path.join(ROOT, 'tmp', file); const ukuran = fs.statSync(full).size
  if (ukuran > maksMB * 1024 * 1024) { fs.unlinkSync(full); return m.reply(`⚠️ File terlalu besar (${formatSize(ukuran)}), batas WhatsApp ±${maksMB}MB.`) }
  const buf = fs.readFileSync(full); fs.unlinkSync(full)
  const cap = `✅ *${nama}*\n📦 ${formatSize(ukuran)} · via ${config.bot.name}`
  if (audio) return m.sendAudio(buf, { mimetype: 'audio/mpeg', ptt: false, fileName: `${nama}.mp3` })
  if (/\.(mp4|mkv|webm|mov)$/i.test(file)) return m.sendVideo(buf, cap)
  return m.sendDoc(buf, file, 'application/octet-stream')
}
const dlPlug = (cmd, aliases, nama, desc, pola, opt = {}) => plug('Downloader', cmd, aliases, desc, async m => {
  const url = urlDari(m); if (!url || (pola && !pola.test(url))) return m.reply(`⬇️ *${nama}*\nKirim link-nya: \`${P}${cmd} <url>\`${opt.audio ? '\n(hasil: audio mp3)' : ''}\n\n⚙️ Butuh yt-dlp: \`pkg install python ffmpeg && pip install -U yt-dlp\``)
  try { return await unduhGenerik(m, { url, audio: !!opt.audio, nama }) } catch (e) {
    if (/yt-dlp belum terpasang/.test(String(e.message))) return m.reply(`⚙️ *Butuh yt-dlp*\n\n\`\`\`pkg install -y python ffmpeg\npip install -U yt-dlp\`\`\`\nLalu ulangi \`${P}${cmd}\`. Cek: ${P}ytdlpinfo`)
    throw e
  }
}, { limit: 1, cooldown: 8 })
export const DL_BARU = [
  dlPlug('fbvideo', ['facebookdl', 'fbdl2', 'fbreels'], 'Facebook Video/Reels', '📘 Unduh video / reels Facebook (publik) 720p', /facebook\.com|fb\.watch|fb\.com/i),
  dlPlug('twvideo', ['twitterdl', 'xvideo', 'xdl'], 'Twitter / X Video', '🐦 Unduh video dari Twitter / X', /twitter\.com|x\.com|t\.co/i),
  dlPlug('igreels', ['reelsdl', 'igvideo2', 'instareels'], 'Instagram Reels', '📸 Unduh reels / video Instagram publik', /instagram\.com/i),
  dlPlug('threadsdl', ['threads', 'threadsvideo'], 'Threads', '🧵 Unduh video dari Threads (Meta)', /threads\.(net|com)/i),
  dlPlug('scdl', ['soundcloud', 'soundclouddl', 'scmp3'], 'SoundCloud', '🎧 Unduh lagu SoundCloud sebagai MP3', /soundcloud\.com/i, { audio: true }),
  dlPlug('pinvideo2', ['pinterestvideo', 'pindlvideo', 'pinvidhd'], 'Pinterest Video', '📌 Unduh video Pinterest (pin.it / pinterest.com)', /pinterest\.|pin\.it/i),
  dlPlug('capcutdl', ['capcut', 'capcuttemplate'], 'CapCut Template', '✂️ Unduh video template CapCut', /capcut\.com/i),
  dlPlug('likeedl', ['likee', 'likeevideo'], 'Likee', '💃 Unduh video Likee tanpa watermark', /likee\.(video|com)|l\.likee/i),
  dlPlug('snackdl', ['snackvideo', 'snack'], 'Snack Video', '🍿 Unduh video Snack Video', /snackvideo\.com|sck\.io/i),
  dlPlug('bilibilidl', ['bilibili', 'bstation', 'bilidl'], 'Bilibili / Bstation', '📺 Unduh video Bilibili / Bstation 720p', /bilibili\.(tv|com)|b23\.tv/i)
]

/* ================================================================== */
/*  3. INTERNET — 10 fitur                                              */
/* ================================================================== */
export const NET_BARU = [
  plug('Internet', 'pendekkanurl', ['urlpendek', 'pendekurl', 'pendek'], '🔗 Pendekkan URL (is.gd / tinyurl)', async m => { const u = urlDari(m); if (!u) return m.reply(`🔗 \`${P}pendekkanurl https://...\``); let hasil; try { const r = await fetch(`https://is.gd/create.php?format=simple&url=${encodeURIComponent(u)}`, { signal: AbortSignal.timeout(15000) }); hasil = (await r.text()).trim(); if (!/^https?:/.test(hasil)) throw 0 } catch { const r = await fetch(`https://tinyurl.com/api-create.php?url=${encodeURIComponent(u)}`, { signal: AbortSignal.timeout(15000) }); hasil = (await r.text()).trim() } return m.reply(`🔗 *URL PENDEK*\n\n${hasil}\n\nAsli: ${truncate(u, 120)}`) }),
  plug('Internet', 'cekupweb', ['isitdown', 'webdown', 'situsdown'], '🟢 Cek apakah sebuah situs sedang up / down + waktu respons & kode HTTP', async m => { let u = (m.args[0] || '').trim(); if (!u) return m.reply(`🟢 \`${P}cekupweb google.com\``); if (!/^https?:/.test(u)) u = 'https://' + u; const t0 = Date.now(); try { const r = await fetch(u, { method: 'HEAD', redirect: 'follow', signal: AbortSignal.timeout(12000), headers: { 'User-Agent': UA } }); return m.reply(`🟢 *${new URL(u).host} UP*\n\n▸ Status: ${r.status} ${r.statusText}\n▸ Respons: ${Date.now() - t0} ms\n▸ Server: ${r.headers.get('server') || '-'}\n▸ Tipe: ${r.headers.get('content-type') || '-'}`) } catch (e) { return m.reply(`🔴 *${new URL(u).host} DOWN / tidak terjangkau*\n\n${truncate(String(e.message), 120)}\n(${Date.now() - t0} ms)`) } }),
  plug('Internet', 'metatag', ['ogpreview', 'previewlink', 'linkinfo'], '🏷️ Ambil judul, deskripsi & gambar Open Graph dari sebuah link (preview)', async m => { const u = urlDari(m); if (!u) return m.reply(`🏷️ \`${P}metatag https://...\``); const r = await fetch(u, { redirect: 'follow', signal: AbortSignal.timeout(15000), headers: { 'User-Agent': UA } }); const html = (await r.text()).slice(0, 200000); const meta = n => html.match(new RegExp(`<meta[^>]+(?:property|name)=["']${n}["'][^>]+content=["']([^"']+)`, 'i'))?.[1] || html.match(new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${n}["']`, 'i'))?.[1]; const title = meta('og:title') || html.match(/<title[^>]*>([^<]+)/i)?.[1] || '-'; const desc = meta('og:description') || meta('description') || '-'; const img = meta('og:image'); const teks = `🏷️ *${truncate(title.trim(), 120)}*\n\n${truncate(desc.trim(), 400)}\n\n▸ Situs: ${meta('og:site_name') || new URL(u).host}\n▸ Tipe: ${meta('og:type') || '-'}\n🔗 ${u}`; if (img) { try { return await m.sendImage(img.startsWith('http') ? img : new URL(img, u).href, teks) } catch {} } return m.reply(teks) }),
  plug('Internet', 'cekemail2', ['validasiemail', 'emailvalid', 'cekmx'], '📧 Validasi format email + cek domain punya MX record (bisa terima email)', async m => { const e = (m.args[0] || '').trim(); const ok = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(e); if (!e) return m.reply(`📧 \`${P}cekemail2 nama@domain.com\``); const dom = e.split('@')[1]; let mx = []; if (ok) { try { const d = await json(`https://dns.google/resolve?name=${dom}&type=MX`); mx = (d.Answer || []).map(a => a.data) } catch {} } return m.reply(`📧 *CEK EMAIL* ${e}\n\n▸ Format: ${ok ? '✅ valid' : '❌ tidak valid'}\n▸ Domain: ${dom || '-'}\n▸ MX record: ${mx.length ? '✅ ' + mx.slice(0, 3).join(', ') : '❌ tidak ada (kemungkinan tidak bisa menerima email)'}\n▸ Disposable: ${/(tempmail|10minutemail|guerrillamail|mailinator|yopmail|trashmail)/i.test(dom || '') ? '⚠️ ya' : 'tidak terdeteksi'}`) }),
  plug('Internet', 'iplokasi', ['geoip', 'ipgeolokasi', 'cekiplokasi'], '🗺️ Lokasi & ISP dari alamat IP / domain (ip-api): .iplokasi 8.8.8.8', async m => { const q = (m.args[0] || '').trim(); const d = await json(`http://ip-api.com/json/${encodeURIComponent(q)}?fields=status,message,country,regionName,city,zip,lat,lon,timezone,isp,org,as,query,proxy,mobile&lang=id`); if (d.status !== 'success') throw new Error(d.message || 'gagal'); return m.reply(`🗺️ *LOKASI IP* ${d.query}\n\n▸ ${d.city}, ${d.regionName}, ${d.country} ${d.zip || ''}\n▸ Koordinat: ${d.lat}, ${d.lon}\n▸ Zona waktu: ${d.timezone}\n▸ ISP: ${d.isp}\n▸ Org/AS: ${d.org || '-'} · ${d.as}\n▸ Proxy/VPN: ${d.proxy ? '⚠️ ya' : 'tidak'} · Seluler: ${d.mobile ? 'ya' : 'tidak'}\n🗺️ https://maps.google.com/?q=${d.lat},${d.lon}`) }),
  plug('Internet', 'dnsall', ['dnsrecord', 'cekdns', 'dnsinfo'], '🌐 Semua record DNS domain (A, AAAA, MX, NS, TXT, CNAME) via DNS over HTTPS', async m => { const dom = (m.args[0] || '').replace(/^https?:\/\//, '').split('/')[0]; if (!dom) return m.reply(`🌐 \`${P}dnsall google.com\``); const tipe = ['A', 'AAAA', 'MX', 'NS', 'TXT', 'CNAME']; const out = []; for (const t of tipe) { try { const d = await json(`https://dns.google/resolve?name=${dom}&type=${t}`); const ans = (d.Answer || []).map(a => truncate(a.data, 80)); if (ans.length) out.push(`*${t}*\n${ans.slice(0, 5).map(a => '  ' + a).join('\n')}`) } catch {} } return m.reply(`🌐 *DNS ${dom}*\n\n${out.join('\n') || 'Tidak ada record / domain tidak ditemukan.'}`) }),
  plug('Internet', 'sslcek', ['ceksertifikat', 'sertifikatssl', 'httpsinfo'], '🔒 Info sertifikat SSL domain: penerbit, masa berlaku, sisa hari (crt.sh)', async m => { const dom = (m.args[0] || '').replace(/^https?:\/\//, '').split('/')[0]; if (!dom) return m.reply(`🔒 \`${P}sslcek github.com\``); const d = await json(`https://crt.sh/?q=${encodeURIComponent(dom)}&output=json`, 25000); if (!Array.isArray(d) || !d.length) throw new Error('sertifikat tidak ditemukan'); const terbaru = d.sort((a, b) => new Date(b.not_after) - new Date(a.not_after))[0]; const sisa = Math.round((new Date(terbaru.not_after) - Date.now()) / 86400e3); return m.reply(`🔒 *SSL ${dom}*\n\n▸ Nama: ${truncate(terbaru.common_name, 60)}\n▸ Penerbit: ${truncate(terbaru.issuer_name.match(/O=([^,]+)/)?.[1] || terbaru.issuer_name, 60)}\n▸ Berlaku: ${terbaru.not_before.slice(0, 10)} → ${terbaru.not_after.slice(0, 10)}\n▸ Sisa: ${sisa > 0 ? `✅ ${sisa} hari` : '❌ kedaluwarsa'}\n▸ Total sertifikat tercatat: ${d.length}\n\nSumber: crt.sh`) }),
  plug('Internet', 'whoisdomain', ['whois2', 'rdap', 'infodomain'], '📇 WHOIS/RDAP domain: registrar, tanggal daftar & kedaluwarsa, status, nameserver', async m => { const dom = (m.args[0] || '').replace(/^https?:\/\//, '').split('/')[0]; if (!dom) return m.reply(`📇 \`${P}whoisdomain google.com\``); const d = await json(`https://rdap.org/domain/${dom}`, 20000); const ev = Object.fromEntries((d.events || []).map(e => [e.eventAction, e.eventDate?.slice(0, 10)])); const reg = (d.entities || []).find(e => (e.roles || []).includes('registrar')); const regNama = reg?.vcardArray?.[1]?.find(v => v[0] === 'fn')?.[3] || reg?.handle || '-'; return m.reply(`📇 *WHOIS ${d.ldhName || dom}*\n\n▸ Registrar: ${regNama}\n▸ Didaftarkan: ${ev.registration || '-'}\n▸ Diperbarui: ${ev['last changed'] || '-'}\n▸ Kedaluwarsa: ${ev.expiration || '-'}\n▸ Status: ${(d.status || []).slice(0, 3).join(', ') || '-'}\n▸ Nameserver: ${(d.nameservers || []).map(n => n.ldhName).slice(0, 4).join(', ') || '-'}`) }),
  plug('Internet', 'useragentparse', ['parseua', 'cekbrowser', 'infoua'], '🧭 Analisis string User-Agent: browser, OS, perangkat (lokal, tanpa API)', m => { const ua = m.q || UA; const os = /android ([\d.]+)/i.test(ua) ? 'Android ' + ua.match(/android ([\d.]+)/i)[1] : /iphone os ([\d_]+)/i.test(ua) ? 'iOS ' + ua.match(/iphone os ([\d_]+)/i)[1].replace(/_/g, '.') : /windows nt ([\d.]+)/i.test(ua) ? 'Windows ' + ({ '10.0': '10/11', '6.3': '8.1', '6.1': '7' }[ua.match(/windows nt ([\d.]+)/i)[1]] || '') : /mac os x/i.test(ua) ? 'macOS' : /linux/i.test(ua) ? 'Linux' : '-'; const br = /edg\/([\d.]+)/i.test(ua) ? 'Edge ' + ua.match(/edg\/([\d.]+)/i)[1] : /opr\/([\d.]+)/i.test(ua) ? 'Opera ' + ua.match(/opr\/([\d.]+)/i)[1] : /chrome\/([\d.]+)/i.test(ua) ? 'Chrome ' + ua.match(/chrome\/([\d.]+)/i)[1] : /firefox\/([\d.]+)/i.test(ua) ? 'Firefox ' + ua.match(/firefox\/([\d.]+)/i)[1] : /safari/i.test(ua) ? 'Safari' : '-'; return m.reply(`🧭 *USER-AGENT*\n\n▸ Browser: ${br}\n▸ OS: ${os}\n▸ Perangkat: ${/mobile/i.test(ua) ? '📱 Mobile' : /tablet|ipad/i.test(ua) ? '📱 Tablet' : '💻 Desktop'}\n▸ Bot: ${/bot|crawl|spider/i.test(ua) ? 'ya' : 'tidak'}\n\n\`${truncate(ua, 200)}\``) }, { limit: 0 }),
  plug('Internet', 'hitungbandwidth', ['waktuunduh', 'estimasidownload', 'kecepatanunduh'], '⏱️ Estimasi waktu unduh file: .hitungbandwidth 2gb 20mbps', m => { const [uk, kc] = m.args; const mu = (uk || '').match(/^([\d.]+)\s*(kb|mb|gb|tb)$/i), mk = (kc || '').match(/^([\d.]+)\s*(kbps|mbps|gbps)$/i); if (!mu || !mk) return m.reply(`⏱️ \`${P}hitungbandwidth 2gb 20mbps\``); const bytes = parseFloat(mu[1]) * ({ kb: 1e3, mb: 1e6, gb: 1e9, tb: 1e12 })[mu[2].toLowerCase()]; const bps = parseFloat(mk[1]) * ({ kbps: 1e3, mbps: 1e6, gbps: 1e9 })[mk[2].toLowerCase()]; const detik = bytes * 8 / bps; return m.reply(`⏱️ *ESTIMASI UNDUH*\n\nUkuran: ${uk.toUpperCase()} · Kecepatan: ${kc}\n\n▸ Ideal: *${formatDuration(detik * 1000)}*\n▸ Realistis (70% kecepatan): ${formatDuration(detik / 0.7 * 1000)}\n▸ Throughput: ${(bps / 8 / 1e6).toFixed(2)} MB/s`) }, { limit: 0 })
]

/* ================================================================== */
/*  4. ISLAMI — 10 fitur (lokal)                                        */
/* ================================================================== */
const DOA_PILIHAN = {
  pagi: ['Allahumma bika ashbahna wa bika amsaina wa bika nahya wa bika namutu wa ilaikan nusyur.', 'Ya Allah, dengan-Mu kami berpagi hari, dengan-Mu kami bersore hari, dengan-Mu kami hidup dan mati, dan kepada-Mu kebangkitan.'],
  sore: ['Allahumma bika amsaina wa bika ashbahna wa bika nahya wa bika namutu wa ilaikal mashir.', 'Ya Allah, dengan-Mu kami bersore hari, dengan-Mu kami berpagi hari, dengan-Mu kami hidup dan mati, dan kepada-Mu tempat kembali.'],
  tidur: ['Bismika Allahumma ahya wa amut.', 'Dengan nama-Mu ya Allah aku hidup dan aku mati.'],
  bangun: ['Alhamdulillahilladzi ahyana ba\'da ma amatana wa ilaihin nusyur.', 'Segala puji bagi Allah yang menghidupkan kami setelah mematikan kami, dan kepada-Nya kebangkitan.'],
  makan: ['Allahumma barik lana fima razaqtana wa qina \'adzaban nar.', 'Ya Allah, berkahilah rezeki yang Engkau berikan kepada kami dan peliharalah kami dari siksa neraka.'],
  bepergian: ['Subhanalladzi sakhkhara lana hadza wa ma kunna lahu muqrinin wa inna ila rabbina lamunqalibun.', 'Maha Suci Allah yang menundukkan kendaraan ini untuk kami, padahal kami tidak mampu menguasainya, dan kepada Tuhan kami, kami kembali.'],
  belajar: ['Rabbi zidni \'ilma warzuqni fahma.', 'Ya Tuhanku, tambahkanlah ilmu kepadaku dan berilah aku pemahaman.'],
  sakit: ['Allahumma rabban nas adzhibil ba\'sa isyfi antasy syafi la syifa\'a illa syifa\'uka syifa\'an la yughadiru saqama.', 'Ya Allah Tuhan manusia, hilangkanlah penyakit, sembuhkanlah, Engkau Maha Penyembuh, tiada kesembuhan selain kesembuhan-Mu, kesembuhan yang tidak meninggalkan penyakit.'],
  hujan: ['Allahumma shayyiban nafi\'a.', 'Ya Allah, turunkanlah hujan yang bermanfaat.'],
  orangtua: ['Rabbighfirli wa liwalidayya warhamhuma kama rabbayani shaghira.', 'Ya Tuhanku, ampunilah aku dan kedua orang tuaku, sayangilah keduanya sebagaimana mereka menyayangiku di waktu kecil.']
}
const HARI_BESAR = [['1 Muharram', 'Tahun Baru Hijriah'], ['10 Muharram', 'Hari Asyura (puasa sunnah)'], ['12 Rabiul Awal', 'Maulid Nabi Muhammad ﷺ'], ['27 Rajab', 'Isra Mi\'raj'], ['15 Sya\'ban', 'Nisfu Sya\'ban'], ['1 Ramadhan', 'Awal puasa Ramadhan'], ['17 Ramadhan', 'Nuzulul Qur\'an'], ['21-29 Ramadhan (ganjil)', 'Lailatul Qadar'], ['1 Syawal', 'Idul Fitri'], ['9 Dzulhijjah', 'Hari Arafah (puasa sunnah)'], ['10 Dzulhijjah', 'Idul Adha'], ['11-13 Dzulhijjah', 'Hari Tasyrik']]
export const ISLAMI_BARU = [
  plug('Islami', 'kalkzakatmal', ['hitungzakatmal', 'nisabemas', 'zakatmalku'], '💰 Hitung zakat mal (2,5%) dengan nisab 85 gram emas: .zakatmal <total harta> [harga emas/gram]', m => { const harta = Number((m.args[0] || '').replace(/\D/g, '')); const emas = Number((m.args[1] || '').replace(/\D/g, '')) || 1350000; if (!harta) return m.reply(`💰 \`${P}kalkzakatmal 150000000\` [harga emas/gram, default 1.350.000]\n(harta = tabungan + emas + investasi − utang jatuh tempo, sudah 1 tahun/haul)`); const nisab = 85 * emas; const wajib = harta >= nisab; return m.reply(`💰 *ZAKAT MAL*\n\n▸ Total harta: Rp ${harta.toLocaleString('id-ID')}\n▸ Nisab (85 g × Rp ${emas.toLocaleString('id-ID')}): Rp ${nisab.toLocaleString('id-ID')}\n▸ Status: ${wajib ? '✅ WAJIB zakat' : '❌ belum mencapai nisab'}\n${wajib ? `▸ Zakat 2,5%: *Rp ${Math.round(harta * 0.025).toLocaleString('id-ID')}*` : ''}\n\n💡 Harga emas hari ini: ${P}hargaemas`) }, { limit: 0 }),
  plug('Islami', 'kalkzakatprofesi', ['hitungzakatgaji', 'zakatgajiku'], '💼 Hitung zakat penghasilan (2,5%) per bulan/tahun dengan nisab 85 g emas per tahun: .zakatprofesi <gaji/bulan> [harga emas]', m => { const gaji = Number((m.args[0] || '').replace(/\D/g, '')); const emas = Number((m.args[1] || '').replace(/\D/g, '')) || 1350000; if (!gaji) return m.reply(`💼 \`${P}kalkzakatprofesi 8000000\``); const nisabBulan = 85 * emas / 12; const wajib = gaji >= nisabBulan; return m.reply(`💼 *ZAKAT PENGHASILAN*\n\n▸ Penghasilan: Rp ${gaji.toLocaleString('id-ID')}/bulan\n▸ Nisab/bulan: Rp ${Math.round(nisabBulan).toLocaleString('id-ID')}\n▸ Status: ${wajib ? '✅ WAJIB' : '❌ belum wajib (boleh infak)'}\n${wajib ? `▸ Zakat/bulan: *Rp ${Math.round(gaji * 0.025).toLocaleString('id-ID')}*\n▸ Zakat/tahun: Rp ${Math.round(gaji * 12 * 0.025).toLocaleString('id-ID')}` : ''}`) }, { limit: 0 }),
  plug('Islami', 'kalkzakatfitrah', ['fitrahkeluarga', 'zakatfitrahku'], '🌾 Hitung zakat fitrah keluarga (2,5 kg beras/jiwa): .zakatfitrah <jumlah jiwa> [harga beras/kg]', m => { const jiwa = parseInt(m.args[0]) || 1; const beras = Number((m.args[1] || '').replace(/\D/g, '')) || 15000; return m.reply(`🌾 *ZAKAT FITRAH*\n\n▸ Jiwa: ${jiwa} orang\n▸ Beras: ${(jiwa * 2.5).toFixed(1)} kg (2,5 kg/jiwa)\n▸ Uang (@Rp ${beras.toLocaleString('id-ID')}/kg): *Rp ${(jiwa * 2.5 * beras).toLocaleString('id-ID')}*\n\n⏰ Ditunaikan sebelum shalat Idul Fitri.`) }, { limit: 0 }),
  plug('Islami', 'doapilihan', ['doasehari', 'doakeadaan', 'doasaat'], '🤲 Doa sesuai keadaan: pagi, sore, tidur, bangun, makan, bepergian, belajar, sakit, hujan, orangtua', m => { const k = (m.args[0] || '').toLowerCase(); const d = DOA_PILIHAN[k]; if (!d) return m.reply(`🤲 \`${P}doapilihan <keadaan>\`\nPilihan: ${Object.keys(DOA_PILIHAN).join(', ')}`); return m.reply(`🤲 *DOA ${k.toUpperCase()}*\n\n_${d[0]}_\n\n"${d[1]}"`) }, { limit: 0 }),
  plug('Islami', 'haribesarislam', ['kalenderislam2', 'haribesar', 'hariislam'], '🗓️ Daftar hari besar Islam & tanggal Hijriahnya + amalan sunnah', m => m.reply(`🗓️ *HARI BESAR ISLAM*\n\n${HARI_BESAR.map(([t, n]) => `▸ *${t}* — ${n}`).join('\n')}\n\n💡 Cek tanggal Hijriah hari ini: ${P}hijriah`), { limit: 0 }),
  plug('Islami', 'targetkhatam', ['khatam', 'jadwalkhatam', 'rencanakhatam'], '📖 Rencana khatam Al-Qur\'an: .targetkhatam <hari> → halaman/hari & juz/hari (mushaf 604 halaman)', m => { const hari = parseInt(m.args[0]) || 30; const hal = 604 / hari; const juz = 30 / hari; const perSholat = hal / 5; return m.reply(`📖 *TARGET KHATAM ${hari} HARI*\n\n▸ ${hal.toFixed(1)} halaman/hari (≈ ${juz.toFixed(2)} juz)\n▸ ≈ ${perSholat.toFixed(1)} halaman tiap selesai shalat fardhu\n▸ ≈ ${Math.ceil(hal / 2)} lembar/hari\n\n${[7, 15, 30, 60, 90].filter(h => h !== hari).map(h => `${h} hari → ${(604 / h).toFixed(1)} hal/hari`).join(' · ')}\n\n💪 Konsisten sedikit lebih baik daripada banyak tapi putus.`) }, { limit: 0 }),
  plug('Islami', 'kalkwaris', ['warisislam', 'faraid', 'bagiwaris'], '⚖️ Kalkulator waris (faraid) kasus umum: .hitungwaris <harta> <istri|suami> <anak laki> <anak perempuan> [ayah 0/1] [ibu 0/1]', m => { const [h, ps, al, ap, ay, ib] = m.args; const harta = Number((h || '').replace(/\D/g, '')); const nAl = parseInt(al) || 0, nAp = parseInt(ap) || 0, ada = { ayah: ay === '1', ibu: ib === '1' }; if (!harta || !ps) return m.reply(`⚖️ \`${P}kalkwaris 600000000 istri 2 1 1 1\`\n(harta, pasangan istri/suami/tidak, anak laki, anak perempuan, ayah 0/1, ibu 0/1)\n_Perhitungan dasar; konsultasikan ke ahli untuk kasus khusus._`); const adaAnak = nAl + nAp > 0; const bagian = {}; let sisa = 1; if (ps === 'istri') { bagian['Istri'] = adaAnak ? 1 / 8 : 1 / 4 } else if (ps === 'suami') { bagian['Suami'] = adaAnak ? 1 / 4 : 1 / 2 } if (ada.ibu) bagian['Ibu'] = adaAnak ? 1 / 6 : 1 / 3; if (ada.ayah) bagian['Ayah'] = adaAnak ? 1 / 6 : 0; sisa -= Object.values(bagian).reduce((a, b) => a + b, 0); if (adaAnak) { const unit = sisa / (nAl * 2 + nAp); if (nAl) bagian[`Anak laki-laki (${nAl})`] = unit * 2 * nAl; if (nAp) bagian[`Anak perempuan (${nAp})`] = unit * nAp } else if (ada.ayah) { bagian['Ayah'] += sisa } else if (sisa > 0) bagian['Sisa (ashabah lain/baitul mal)'] = sisa; return m.reply(`⚖️ *PEMBAGIAN WARIS* (harta Rp ${harta.toLocaleString('id-ID')})\n\n${Object.entries(bagian).map(([k, v]) => `▸ ${k}: ${(v * 100).toFixed(1)}% = *Rp ${Math.round(v * harta).toLocaleString('id-ID')}*`).join('\n')}\n\n_Sudah dikurangi utang & wasiat? Konsultasikan ke ustadz/ahli faraid untuk kasus lengkap._`) }, { limit: 0 }),
  plug('Islami', 'puasaqadha', ['hitungqadha', 'qadha', 'utangpuasa'], '🌙 Hitung utang puasa & fidyah: .puasaqadha <hari utang> [harga makan/porsi]', m => { const hari = parseInt(m.args[0]); const porsi = Number((m.args[1] || '').replace(/\D/g, '')) || 25000; if (!hari) return m.reply(`🌙 \`${P}puasaqadha 7\` [harga makan/porsi]`); const sekarang = new Date(); const bulanTersisa = 12; return m.reply(`🌙 *QADHA PUASA ${hari} HARI*\n\n▸ Qadha: ${hari} hari puasa pengganti (wajib bagi yang mampu)\n▸ Fidyah (jika tidak mampu berpuasa): ${hari} × 1 porsi makan ≈ *Rp ${(hari * porsi).toLocaleString('id-ID')}*\n▸ Saran jadwal: Senin & Kamis → selesai ±${Math.ceil(hari / 2)} minggu\n▸ Atau 3 hari/minggu → ±${Math.ceil(hari / 3)} minggu\n\n💡 Segerakan sebelum Ramadhan berikutnya.`) }, { limit: 0 }),
  plug('Islami', 'adzanoffset', ['waktuimsak', 'jadwalimsak', 'waktudhuha'], '🕌 Hitung imsak (−10 menit dari Subuh) & waktu dhuha/tahajud dari jadwal shalat kota: .adzanoffset Medan', async m => { const { prayerTimes } = await import('../lib/islami.js'); const kota = m.q || 'Medan'; const d = await prayerTimes(kota); const t = d?.times || d?.timings || d; const geser = (jam, mnt) => { const [h, mi] = String(jam).slice(0, 5).split(':').map(Number); const tot = (h * 60 + mi + mnt + 1440) % 1440; return `${String(Math.floor(tot / 60)).padStart(2, '0')}:${String(tot % 60).padStart(2, '0')}` }; const subuh = t.Fajr || t.subuh, terbit = t.Sunrise || t.terbit, isya = t.Isha || t.isya, maghrib = t.Maghrib || t.maghrib; return m.reply(`🕌 *WAKTU TAMBAHAN — ${kota.toUpperCase()}*\n\n▸ Imsak: *${geser(subuh, -10)}* (Subuh ${String(subuh).slice(0, 5)})\n▸ Dhuha mulai: ${geser(terbit, 15)} (terbit ${String(terbit).slice(0, 5)})\n▸ Dhuha terbaik: ${geser(terbit, 120)}\n▸ Sepertiga malam terakhir (tahajud): ±${geser(maghrib, Math.round((((24 * 60 + (Number(String(subuh).slice(0, 2)) * 60 + Number(String(subuh).slice(3, 5)))) - (Number(String(maghrib).slice(0, 2)) * 60 + Number(String(maghrib).slice(3, 5)))) % 1440) * 2 / 3))}\n▸ Isya: ${String(isya).slice(0, 5)}\n\nJadwal lengkap: ${P}sholat ${kota}`) }),
  plug('Islami', 'hitungtasbih', ['tasbihdigital', 'counterdzikir', 'dzikircounter'], '📿 Tasbih digital pribadi: .hitungtasbih [+n|reset] — hitung dzikir tersimpan per user', m => { const u = getUser(K(m)); u.tasbih = u.tasbih || { n: 0, total: 0 }; const a = (m.args[0] || '+1'); if (a === 'reset') { u.tasbih.n = 0; saveDB('users'); return m.reply('📿 Tasbih direset ke 0.') } const tambah = Math.min(1000, Math.max(1, parseInt(a.replace('+', '')) || 1)); u.tasbih.n += tambah; u.tasbih.total += tambah; saveDB('users'); const n = u.tasbih.n; const putaran = Math.floor(n / 33); return m.reply(`📿 *TASBIH DIGITAL*\n\nHitungan: *${n}* ${n % 33 === 0 && n ? '✅ genap 33' : `(${33 - n % 33} lagi ke ${putaran + 1}×33)`}\nPutaran 33: ${putaran} · Total seumur: ${u.tasbih.total}\n\n\`${P}hitungtasbih +33\` · \`reset\``) }, { limit: 0 })
]

/* ================================================================== */
/*  5. MAIN MENU — 10 fitur                                             */
/* ================================================================== */
const semua = () => listPlugins()
const ikonKat = { 'RPG Menu': '⚔️', Games: '🎮', 'Fun Menu': '🎉', Premium: '💎', 'User Menu': '👤', 'Group Menu': '👥', 'Owner Menu': '👑', Tools: '🧰', 'AI Menu': '🤖', 'Sticker Menu': '🎨', 'Info Menu': 'ℹ️', Downloader: '⬇️', Internet: '🌐', Islami: '🕌', 'Main Menu': '🏠' }
const fav = u => { u.favorit = u.favorit || []; return u.favorit }
export const MAIN_BARU = [
  plug('Main Menu', 'carimenu2', ['findcmd', 'cariapa', 'fiturapa'], '🔍 Cari perintah berdasarkan kata kunci di nama/deskripsi: .carimenu stiker', m => { const q = (m.q || '').toLowerCase(); if (!q) return m.reply(`🔍 \`${P}carimenu2 download\``); const hasil = semua().filter(p => p.command.some(c => c.includes(q)) || (p.description || '').toLowerCase().includes(q)).slice(0, 25); if (!hasil.length) return m.reply(`Tidak ada perintah cocok "${q}".`); return m.reply(`🔍 *HASIL "${q}"* (${hasil.length})\n\n${hasil.map(p => `▸ \`${P}${p.command[0]}\` — ${truncate(p.description || '', 60)}`).join('\n')}`) }, { limit: 0 }),
  plug('Main Menu', 'menuacak', ['fituracak', 'randomcmd', 'cobaini'], '🎲 Tampilkan 5 perintah acak untuk dicoba (kecuali owner)', m => { const list = semua().filter(p => !p.owner && p.category !== 'Owner Menu').sort(() => Math.random() - 0.5).slice(0, 5); return m.sendButtons({ title: '🎲 Coba fitur ini', text: `🎲 *5 FITUR ACAK UNTUKMU*\n\n${list.map(p => `${ikonKat[p.category] || '▸'} \`${P}${p.command[0]}\`\n   ${truncate(p.description || '', 70)}`).join('\n')}`, footer: config.bot.footer, buttons: list.slice(0, 5).map(p => ({ text: truncate(`${ikonKat[p.category] || ''} ${p.command[0]}`, 20), id: `${P}${p.command[0]}` })).concat([{ text: '🎲 Acak lagi', id: `${P}menuacak` }]) }).catch(() => m.reply(list.map(p => `▸ ${P}${p.command[0]}`).join('\n'))) }, { limit: 0 }),
  plug('Main Menu', 'menuterbaru', ['fiturbaru', 'whatsnew', 'baru'], '🆕 Ringkasan fitur baru versi ini (v7.9.0): 4 game rupa asli, Subway 3D, 150 fitur baru', m => m.reply(`🆕 *BARU DI ${config.bot.name} v${config.bot.version || '7.9.0'}*\n\n🎮 *Game HTML rupa asli:* ${P}subway (3D baru!) · ${P}candycrush · ${P}templerun · ${P}angrybirds · ${P}superjump\n\n✨ *150 fitur baru (10 per kategori):*\n⚔️ RPG: ${P}lotere ${P}rampok ${P}deposito ${P}kebun ${P}ternak ${P}gacha ${P}bounty ${P}sedekah ${P}nikah ${P}kirimhadiah\n🎮 Games: ${P}tebakhewan ${P}tebakbuah ${P}tebakkotanegara ${P}tebaktahun ${P}katarahasia ${P}tebakwarna ${P}lawankata ${P}lengkapiperibahasa ${P}singkatanapa ${P}kuishitungcepat\n🎉 Fun: ${P}julukan ${P}kutukan ${P}hukuman ${P}ramalancinta ${P}tanyadukun ${P}cekhoki ${P}mantra ${P}cocoknama ${P}tebakusia ${P}siapayang\n💎 Premium: ${P}premkuota ${P}premnote ${P}premtodo ${P}premlucky ${P}premwish ${P}premstat ${P}premrank ${P}premboost ${P}premhitung ${P}premkotak\n👤 User: ${P}setnick ${P}setgender ${P}setkota ${P}setultah ${P}sethobi ${P}biodata ${P}streak ${P}lencana ${P}ultahku ${P}aktivitasku\n👥 Group: ${P}badword ${P}antisticker ${P}antimedia ${P}jammalam ${P}autoreply ${P}peringatan ${P}pilihadmin ${P}sambutan ${P}setaturansingkat ${P}statgrupv9\n👑 Owner: ${P}bcpremium ${P}bcaktif ${P}userinfo ${P}setkoin ${P}setlevelrpg ${P}resetdatarpg ${P}totalchat ${P}kesehatanbot ${P}pesanpembuka ${P}kuncifitur\n🧰 Tools: ${P}cicilan ${P}diskon ${P}ppn ${P}kalori ${P}bungamajemuk ${P}hariapa ${P}satuan ${P}katasandi ${P}ceksandi ${P}jadwalkerja\n🤖 AI: ${P}koreksi ${P}jelaskan ${P}kodeai ${P}idenama ${P}debat ${P}cerpenai ${P}emailai ${P}resepai ${P}kuisai ${P}rencanaai\n🎨 Sticker: ${P}ssepia ${P}spixel ${P}sbingkai ${P}sbulatbingkai ${P}skartun ${P}sneon ${P}sdingin ${P}shangat ${P}svignette ${P}scermin4\nℹ️ Info: ${P}gempa ${P}gempaterbaru15 ${P}wikiringkas ${P}cuacajam ${P}kualitasudara ${P}kripto ${P}hargaemas ${P}profilnegara ${P}hariini2 ${P}nomorpenting\n⬇️ Download: ${P}fbvideo ${P}twvideo ${P}igreels ${P}threadsdl ${P}scdl ${P}pinvideo2 ${P}capcutdl ${P}likeedl ${P}snackdl ${P}bilibilidl\n🌐 Internet: ${P}pendekkanurl ${P}cekupweb ${P}metatag ${P}cekemail2 ${P}iplokasi ${P}dnsall ${P}sslcek ${P}whoisdomain ${P}useragentparse ${P}hitungbandwidth\n🕌 Islami: ${P}kalkzakatmal ${P}kalkzakatprofesi ${P}kalkzakatfitrah ${P}doapilihan ${P}haribesarislam ${P}targetkhatam ${P}kalkwaris ${P}puasaqadha ${P}adzanoffset ${P}hitungtasbih\n🏠 Menu: ${P}carimenu2 ${P}menuacak ${P}menuterbaru ${P}favorit ${P}menupopuler ${P}menuringkas2 ${P}menukategori ${P}menuhitung ${P}menusaya ${P}menuhelp`), { limit: 0 }),
  plug('Main Menu', 'favorit', ['fav', 'menufavorit', 'bookmarkcmd'], '⭐ Simpan perintah favoritmu: .favorit tambah <cmd> | hapus <cmd> | (kosong = tampilkan tombol favorit)', m => { const u = getUser(K(m)); const f = fav(u); const [a, b] = m.args; if (a === 'tambah' && b) { const c = b.replace(P, '').toLowerCase(); if (!semua().some(p => p.command.includes(c))) return m.reply('Perintah tidak ditemukan.'); if (f.length >= 10) return m.reply('Maks 10 favorit.'); if (!f.includes(c)) f.push(c); saveDB('users'); return m.reply(`⭐ \`${P}${c}\` ditambah ke favorit (${f.length}/10).`) } if (a === 'hapus' && b) { u.favorit = f.filter(c => c !== b.replace(P, '').toLowerCase()); saveDB('users'); return m.reply('🗑️ Dihapus.') } if (!f.length) return m.reply(`⭐ Belum ada favorit.\n\`${P}favorit tambah tebakkata\``); return m.sendButtons({ title: '⭐ Favoritku', text: `⭐ *PERINTAH FAVORITMU*\n\n${f.map(c => `▸ ${P}${c}`).join('\n')}`, footer: config.bot.footer, buttons: f.slice(0, 10).map(c => ({ text: truncate(c, 20), id: `${P}${c}` })) }).catch(() => m.reply(f.map(c => `▸ ${P}${c}`).join('\n'))) }, { limit: 0 }),
  plug('Main Menu', 'menupopuler', ['populer', 'fiturpopuler', 'cmdpopuler'], '🔥 15 perintah paling sering dipakai di bot ini (dari statistik)', m => { const st = getStats(); const top = Object.entries(st.commands || {}).sort((a, b) => b[1] - a[1]).slice(0, 15); if (!top.length) return m.reply('Belum ada statistik.'); return m.reply(`🔥 *PERINTAH TERPOPULER*\n\n${top.map(([c, n], i) => `${i + 1}. \`${P}${c}\` — ${n}×`).join('\n')}\n\nTotal ${st.total || 0} perintah dijalankan.`) }, { limit: 0 }),
  plug('Main Menu', 'menuringkas2', ['menucepat', 'quickmenu', 'menusingkat'], '⚡ Menu super ringkas: 1 baris per kategori dengan 3 perintah populer + jumlah', m => { const st = getStats().commands || {}; const cats = [...categories()].sort((a, b) => b[1].length - a[1].length); return m.reply(`⚡ *MENU RINGKAS — ${config.bot.name}*\n\n${cats.map(([k, l]) => { const top = l.slice().sort((a, b) => (st[b.command[0]] || 0) - (st[a.command[0]] || 0)).slice(0, 3).map(p => P + p.command[0]).join(' '); return `${ikonKat[k] || '▸'} *${k}* (${l.length}) — ${top}` }).join('\n')}\n\nKetik \`${P}menu\` untuk tampilan lengkap.`) }, { limit: 0 }),
  plug('Main Menu', 'menukategori', ['listkategori', 'kategorilist', 'menukat2'], '📂 Tampilkan semua perintah satu kategori sebagai list tombol: .menukategori tools', m => { const q = (m.q || '').toLowerCase(); const cat = [...categories().keys()].find(k => k.toLowerCase() === q || k.toLowerCase().startsWith(q) || k.toLowerCase().includes(q)); if (!q || !cat) return m.reply(`📂 \`${P}menukategori <nama>\`\n${[...categories().keys()].map(k => `${ikonKat[k] || '▸'} ${k}`).join(' · ')}`); const list = categories().get(cat); const bag = []; for (let i = 0; i < list.length; i += 40) bag.push(list.slice(i, i + 40)); return m.sendList({ title: `${ikonKat[cat] || '📂'} ${cat}`, text: `📂 *${cat.toUpperCase()}* — ${list.length} perintah\nPilih untuk langsung menjalankan.`, footer: config.bot.footer, buttonText: `📂 ${cat} (${list.length})`, sections: bag.map((b, i) => ({ title: `${cat} ${bag.length > 1 ? i + 1 : ''}`.trim(), rows: b.map(p => ({ title: `${P}${p.command[0]}`, description: truncate(p.description || '', 70), id: `${P}${p.command[0]}` })) })) }).catch(() => m.reply(list.map(p => `▸ ${P}${p.command[0]}`).join('\n'))) }, { limit: 0 }),
  plug('Main Menu', 'menuhitung', ['statistikmenu', 'hitungmenu', 'menustat'], '🔢 Statistik menu: total perintah, alias, per kategori, yang butuh admin/owner/premium', m => { const all = semua(); const alias = all.reduce((a, p) => a + p.command.length, 0); return m.reply(`🔢 *STATISTIK MENU*\n\n▸ Perintah utama: *${all.length}*\n▸ Total alias: ${alias}\n▸ Kategori: ${categories().size}\n▸ Khusus owner: ${all.filter(p => p.owner).length} · admin: ${all.filter(p => p.admin).length} · premium: ${all.filter(p => p.premium).length} · grup: ${all.filter(p => p.group).length}\n▸ Gratis (limit 0): ${all.filter(p => (p.limit ?? 1) === 0).length}\n\n*Per kategori:*\n${[...categories()].sort((a, b) => b[1].length - a[1].length).map(([k, l]) => `${ikonKat[k] || '▸'} ${k}: ${l.length}`).join('\n')}`) }, { limit: 0 }),
  plug('Main Menu', 'menusaya', ['menuku', 'menupribadi', 'dashboard'], '🧑‍💻 Dashboard pribadi: status akun, limit, favorit, streak, RPG, & perintah yang bisa kamu akses', m => { const u = getUser(K(m)); const r = u.rpg || {}; const bisa = semua().filter(p => !(p.owner && !m.isOwner) && !(p.premium && !m.isPremium) && !(p.group && !m.isGroup)).length; return m.sendButtons({ title: '🧑‍💻 Menu Saya', text: `🧑‍💻 *DASHBOARD* — ${m.pushName || 'kamu'}\n\n▸ Status: ${m.isOwner ? '👑 Owner' : m.isPremium ? '💎 Premium' : '👤 Free'}\n▸ Limit: ${m.isPremium ? '∞' : u.limit}\n▸ Level ${u.level || 1} · RPG Lv ${r.level || 1} · ${(r.money || 0).toLocaleString('id-ID')} koin\n▸ Streak: ${u.profil?.streak?.n || 0} hari 🔥\n▸ Favorit: ${(u.favorit || []).length}\n▸ Perintah bisa diakses: ${bisa} dari ${semua().length}\n\nPintasan di bawah 👇`, footer: config.bot.footer, buttons: [{ text: '🪪 Profil', id: `${P}profile` }, { text: '⭐ Favorit', id: `${P}favorit` }, { text: '🔥 Streak', id: `${P}streak` }, { text: '⚔️ RPG', id: `${P}rpgmenu1` }, { text: '🏠 Menu', id: `${P}menu` }] }).catch(() => m.reply('Gunakan .menu')) }, { limit: 0 }),
  plug('Main Menu', 'menuhelp', ['carabot', 'panduanbot', 'tutorialbot'], '📘 Panduan singkat memakai bot: prefix, tombol, limit, premium, game HTML, RPG, laporan bug', m => m.reply(`📘 *PANDUAN ${config.bot.name}*\n\n1️⃣ Semua perintah diawali \`${P}\` — contoh \`${P}menu\`.\n2️⃣ Menu berbentuk *tombol/list*: cukup ketuk, tidak perlu mengetik.\n3️⃣ *Limit* dipakai tiap perintah berbayar; reset harian. Premium = tanpa limit (\`${P}premmenu\`).\n4️⃣ *Game HTML* (\`${P}arcade\`) jalan langsung di chat — pakai D-pad di bawah layar game.\n5️⃣ *RPG*: mulai dari \`${P}rpgmenu1\`, kerja (\`${P}kerja\`), berkebun (\`${P}kebun\`), kasino, bank (\`${P}deposito\`).\n6️⃣ Cari fitur: \`${P}carimenu2 <kata>\` · fitur baru: \`${P}menuterbaru\` · acak: \`${P}menuacak\`.\n7️⃣ Detail sebuah perintah: \`${P}menu <perintah>\`.\n8️⃣ Ada masalah? \`${P}owner\` untuk kontak developer.\n\nSelamat mencoba! 🚀`), { limit: 0 })
]

export default { INFO_BARU, DL_BARU, NET_BARU, ISLAMI_BARU, MAIN_BARU }
